export type BusDirection = "solan_to_shimla" | "shimla_to_solan";
export type BusTimeOfDay = "all" | "morning" | "afternoon" | "evening";
export type BusCategory = "all" | "ordinary" | "express" | "deluxe" | "volvo";

export interface BusScheduleItem {
  id: string;
  direction: BusDirection;
  operator: string;
  busType: "Ordinary" | "Express" | "Deluxe" | "Volvo AC";
  fromStation: string;
  departureTime: string;
  waknaghatTime: string; // Approximate time at Waknaghat Chowk (NH-5 JUIT link)
  toStation: string;
  arrivalTime: string;
  fareFromWaknaghat: string;
  fullFare: string;
  timeOfDay: "morning" | "afternoon" | "evening";
  frequency: string;
  routeVia: string;
  keyStops: string[];
  contactNumber?: string;
  note?: string;
}

export const BUS_ENQUIRY_CONTACTS = [
  {
    station: "Solan HRTC Old Bus Stand",
    phone: "01792-220171",
    timing: "06:00 AM – 09:30 PM",
    desc: "Inquiry for all outbound buses towards Waknaghat, Kandaghat & Shimla",
  },
  {
    station: "Shimla ISBT Tutikandi",
    phone: "0177-2806587",
    timing: "24x7 Counter",
    desc: "Main inter-state terminal for all Solan/Chandigarh bound buses",
  },
  {
    station: "Shimla Old Bus Stand (Cart Road)",
    phone: "0177-2656326",
    timing: "06:00 AM – 09:00 PM",
    desc: "Local mudrika & frequent Solan-bound shuttle buses",
  },
  {
    station: "HRTC Central Helpline",
    phone: "1800-180-8185",
    timing: "Toll-Free (24x7)",
    desc: "Himachal Pradesh State Transport centralized assistance",
  },
];

export const SOLAN_SHIMLA_BUS_SCHEDULE: BusScheduleItem[] = [
  // ══════════════════════════════════════════════════════════════════
  // DIRECTION 1: SOLAN ➔ WAKNAGHAT CHOWK ➔ SHIMLA
  // ══════════════════════════════════════════════════════════════════
  {
    id: "s2s-01",
    direction: "solan_to_shimla",
    operator: "HRTC Ordinary",
    busType: "Ordinary",
    fromStation: "Solan Old Bus Stand",
    departureTime: "05:45 AM",
    waknaghatTime: "06:20 AM",
    toStation: "Shimla ISBT Tutikandi",
    arrivalTime: "07:15 AM",
    fareFromWaknaghat: "₹35",
    fullFare: "₹75",
    timeOfDay: "morning",
    frequency: "Daily",
    routeVia: "Solan Bypass ➔ Kandaghat ➔ Waknaghat Chowk ➔ Shoghi ➔ Taradevi",
    keyStops: ["Solan", "Kandaghat", "Waknaghat Chowk", "Shoghi", "Shimla ISBT"],
    note: "First early-morning connection to Shimla.",
  },
  {
    id: "s2s-02",
    direction: "solan_to_shimla",
    operator: "Private Mudrika",
    busType: "Ordinary",
    fromStation: "Solan Mall Road Stop",
    departureTime: "06:30 AM",
    waknaghatTime: "07:05 AM",
    toStation: "Shimla Old Bus Stand",
    arrivalTime: "08:00 AM",
    fareFromWaknaghat: "₹35",
    fullFare: "₹70",
    timeOfDay: "morning",
    frequency: "Daily",
    routeVia: "Solan ➔ Salogra ➔ Kandaghat ➔ Waknaghat ➔ Taradevi ➔ Cart Road",
    keyStops: ["Solan", "Salogra", "Kandaghat", "Waknaghat Chowk", "Taradevi", "Cart Road"],
    note: "Direct to Shimla Old Bus Stand / Cart Road.",
  },
  {
    id: "s2s-03",
    direction: "solan_to_shimla",
    operator: "HRTC Express",
    busType: "Express",
    fromStation: "Solan New Bus Stand",
    departureTime: "07:15 AM",
    waknaghatTime: "07:50 AM",
    toStation: "Shimla ISBT Tutikandi",
    arrivalTime: "08:40 AM",
    fareFromWaknaghat: "₹40",
    fullFare: "₹85",
    timeOfDay: "morning",
    frequency: "Daily",
    routeVia: "NH-5 Flyover ➔ Kandaghat ➔ Waknaghat Chowk ➔ Shoghi",
    keyStops: ["Solan", "Kandaghat", "Waknaghat Chowk", "Shimla ISBT"],
    note: "Fast morning service for college commuters and office goers.",
  },
  {
    id: "s2s-04",
    direction: "solan_to_shimla",
    operator: "HRTC Ordinary (Student Prime)",
    busType: "Ordinary",
    fromStation: "Solan Old Bus Stand",
    departureTime: "08:00 AM",
    waknaghatTime: "08:35 AM",
    toStation: "Shimla ISBT Tutikandi",
    arrivalTime: "09:30 AM",
    fareFromWaknaghat: "₹35",
    fullFare: "₹75",
    timeOfDay: "morning",
    frequency: "Daily",
    routeVia: "Solan ➔ Barog Bypass ➔ Kandaghat ➔ Waknaghat Chowk ➔ Shoghi ➔ Taradevi",
    keyStops: ["Solan", "Kandaghat", "Waknaghat Chowk", "Shoghi", "Shimla ISBT"],
    note: "Very popular student bus with guaranteed halt at Waknaghat Chowk.",
  },
  {
    id: "s2s-05",
    direction: "solan_to_shimla",
    operator: "HRTC Semi-Deluxe",
    busType: "Deluxe",
    fromStation: "Solan Bypass",
    departureTime: "08:45 AM",
    waknaghatTime: "09:20 AM",
    toStation: "Shimla ISBT Tutikandi",
    arrivalTime: "10:10 AM",
    fareFromWaknaghat: "₹50",
    fullFare: "₹105",
    timeOfDay: "morning",
    frequency: "Daily",
    routeVia: "Chandigarh-Shimla Highway Corridor via Waknaghat",
    keyStops: ["Solan", "Waknaghat Chowk", "Taradevi", "Shimla ISBT"],
    note: "Cushioned seating, stops on wave at Waknaghat Chowk.",
  },
  {
    id: "s2s-06",
    direction: "solan_to_shimla",
    operator: "HRTC Himsuta Volvo",
    busType: "Volvo AC",
    fromStation: "Solan Bypass (Kumarhatti)",
    departureTime: "09:30 AM",
    waknaghatTime: "10:05 AM",
    toStation: "Shimla ISBT Tutikandi",
    arrivalTime: "10:50 AM",
    fareFromWaknaghat: "₹110",
    fullFare: "₹220",
    timeOfDay: "morning",
    frequency: "Daily",
    routeVia: "NH-5 Express Corridor",
    keyStops: ["Solan Bypass", "Waknaghat Chowk", "Shimla ISBT"],
    note: "AC Volvo service; pre-booking available on hrtchp.com.",
  },
  {
    id: "s2s-07",
    direction: "solan_to_shimla",
    operator: "Private Local Shuttle",
    busType: "Ordinary",
    fromStation: "Solan Old Bus Stand",
    departureTime: "10:15 AM",
    waknaghatTime: "10:50 AM",
    toStation: "Shimla Old Bus Stand",
    arrivalTime: "11:45 AM",
    fareFromWaknaghat: "₹35",
    fullFare: "₹75",
    timeOfDay: "morning",
    frequency: "Daily",
    routeVia: "Solan ➔ Kandaghat ➔ Waknaghat Chowk ➔ Shoghi ➔ Cart Road",
    keyStops: ["Solan", "Kandaghat", "Waknaghat Chowk", "Shoghi", "Shimla Old"],
  },
  {
    id: "s2s-08",
    direction: "solan_to_shimla",
    operator: "HRTC Ordinary",
    busType: "Ordinary",
    fromStation: "Solan New Bus Stand",
    departureTime: "11:00 AM",
    waknaghatTime: "11:35 AM",
    toStation: "Shimla ISBT Tutikandi",
    arrivalTime: "12:30 PM",
    fareFromWaknaghat: "₹35",
    fullFare: "₹75",
    timeOfDay: "morning",
    frequency: "Daily",
    routeVia: "Solan ➔ Kandaghat ➔ Waknaghat Chowk ➔ Taradevi ➔ ISBT",
    keyStops: ["Solan", "Kandaghat", "Waknaghat Chowk", "Taradevi", "Shimla ISBT"],
  },
  {
    id: "s2s-09",
    direction: "solan_to_shimla",
    operator: "HRTC Express",
    busType: "Express",
    fromStation: "Solan Old Bus Stand",
    departureTime: "12:00 PM",
    waknaghatTime: "12:35 PM",
    toStation: "Shimla ISBT Tutikandi",
    arrivalTime: "01:25 PM",
    fareFromWaknaghat: "₹40",
    fullFare: "₹85",
    timeOfDay: "afternoon",
    frequency: "Daily",
    routeVia: "NH-5 Corridor via Waknaghat Chowk",
    keyStops: ["Solan", "Kandaghat", "Waknaghat Chowk", "Shimla ISBT"],
    note: "Afternoon express connecting to upper Himachal routes.",
  },
  {
    id: "s2s-10",
    direction: "solan_to_shimla",
    operator: "Private Mudrika",
    busType: "Ordinary",
    fromStation: "Solan Mall Road",
    departureTime: "01:00 PM",
    waknaghatTime: "01:35 PM",
    toStation: "Shimla Old Bus Stand",
    arrivalTime: "02:30 PM",
    fareFromWaknaghat: "₹35",
    fullFare: "₹75",
    timeOfDay: "afternoon",
    frequency: "Daily",
    routeVia: "Solan ➔ Salogra ➔ Kandaghat ➔ Waknaghat ➔ Cart Road",
    keyStops: ["Solan", "Kandaghat", "Waknaghat Chowk", "Cart Road"],
  },
  {
    id: "s2s-11",
    direction: "solan_to_shimla",
    operator: "HRTC Ordinary",
    busType: "Ordinary",
    fromStation: "Solan Old Bus Stand",
    departureTime: "02:00 PM",
    waknaghatTime: "02:35 PM",
    toStation: "Shimla ISBT Tutikandi",
    arrivalTime: "03:30 PM",
    fareFromWaknaghat: "₹35",
    fullFare: "₹75",
    timeOfDay: "afternoon",
    frequency: "Daily",
    routeVia: "Solan ➔ Kandaghat ➔ Waknaghat Chowk ➔ Shoghi ➔ ISBT",
    keyStops: ["Solan", "Kandaghat", "Waknaghat Chowk", "Shoghi", "Shimla ISBT"],
  },
  {
    id: "s2s-12",
    direction: "solan_to_shimla",
    operator: "HRTC Express (Post-Lab Commuter)",
    busType: "Express",
    fromStation: "Solan Bypass",
    departureTime: "03:15 PM",
    waknaghatTime: "03:50 PM",
    toStation: "Shimla ISBT Tutikandi",
    arrivalTime: "04:40 PM",
    fareFromWaknaghat: "₹40",
    fullFare: "₹85",
    timeOfDay: "afternoon",
    frequency: "Daily",
    routeVia: "NH-5 Highway Corridor",
    keyStops: ["Solan", "Waknaghat Chowk", "Taradevi", "Shimla ISBT"],
    note: "Matches the end of afternoon university lab sessions.",
  },
  {
    id: "s2s-13",
    direction: "solan_to_shimla",
    operator: "HRTC Semi-Deluxe",
    busType: "Deluxe",
    fromStation: "Solan Old Bus Stand",
    departureTime: "04:15 PM",
    waknaghatTime: "04:50 PM",
    toStation: "Shimla ISBT Tutikandi",
    arrivalTime: "05:45 PM",
    fareFromWaknaghat: "₹50",
    fullFare: "₹105",
    timeOfDay: "afternoon",
    frequency: "Daily",
    routeVia: "Solan ➔ Kandaghat ➔ Waknaghat Chowk ➔ Shoghi ➔ ISBT",
    keyStops: ["Solan", "Waknaghat Chowk", "Shoghi", "Shimla ISBT"],
    note: "Prime evening weekend trip departure to Shimla.",
  },
  {
    id: "s2s-14",
    direction: "solan_to_shimla",
    operator: "HRTC Ordinary",
    busType: "Ordinary",
    fromStation: "Solan New Bus Stand",
    departureTime: "05:15 PM",
    waknaghatTime: "05:50 PM",
    toStation: "Shimla Old Bus Stand",
    arrivalTime: "06:45 PM",
    fareFromWaknaghat: "₹35",
    fullFare: "₹75",
    timeOfDay: "evening",
    frequency: "Daily",
    routeVia: "Solan ➔ Kandaghat ➔ Waknaghat Chowk ➔ Cart Road",
    keyStops: ["Solan", "Kandaghat", "Waknaghat Chowk", "Cart Road"],
  },
  {
    id: "s2s-15",
    direction: "solan_to_shimla",
    operator: "HRTC Himsuta Volvo",
    busType: "Volvo AC",
    fromStation: "Solan Bypass",
    departureTime: "06:00 PM",
    waknaghatTime: "06:35 PM",
    toStation: "Shimla ISBT Tutikandi",
    arrivalTime: "07:20 PM",
    fareFromWaknaghat: "₹110",
    fullFare: "₹220",
    timeOfDay: "evening",
    frequency: "Daily",
    routeVia: "NH-5 Express Corridor",
    keyStops: ["Solan Bypass", "Waknaghat Chowk", "Shimla ISBT"],
    note: "Evening AC connection from Delhi/Chandigarh to Shimla.",
  },
  {
    id: "s2s-16",
    direction: "solan_to_shimla",
    operator: "HRTC Ordinary",
    busType: "Ordinary",
    fromStation: "Solan Old Bus Stand",
    departureTime: "07:00 PM",
    waknaghatTime: "07:35 PM",
    toStation: "Shimla ISBT Tutikandi",
    arrivalTime: "08:30 PM",
    fareFromWaknaghat: "₹35",
    fullFare: "₹75",
    timeOfDay: "evening",
    frequency: "Daily",
    routeVia: "Solan ➔ Kandaghat ➔ Waknaghat Chowk ➔ Shoghi ➔ ISBT",
    keyStops: ["Solan", "Kandaghat", "Waknaghat Chowk", "Shoghi", "Shimla ISBT"],
  },
  {
    id: "s2s-17",
    direction: "solan_to_shimla",
    operator: "HRTC Ordinary (Night Last Regular)",
    busType: "Ordinary",
    fromStation: "Solan Old Bus Stand",
    departureTime: "08:30 PM",
    waknaghatTime: "09:05 PM",
    toStation: "Shimla ISBT Tutikandi",
    arrivalTime: "09:55 PM",
    fareFromWaknaghat: "₹40",
    fullFare: "₹80",
    timeOfDay: "evening",
    frequency: "Daily",
    routeVia: "Solan ➔ Kandaghat ➔ Waknaghat Chowk ➔ Shimla ISBT",
    keyStops: ["Solan", "Kandaghat", "Waknaghat Chowk", "Shimla ISBT"],
    note: "Last regular scheduled ordinary bus from Solan to Shimla.",
  },

  // ══════════════════════════════════════════════════════════════════
  // DIRECTION 2: SHIMLA ➔ WAKNAGHAT CHOWK ➔ SOLAN
  // ══════════════════════════════════════════════════════════════════
  {
    id: "s2s-18",
    direction: "shimla_to_solan",
    operator: "HRTC Ordinary",
    busType: "Ordinary",
    fromStation: "Shimla ISBT Tutikandi",
    departureTime: "06:00 AM",
    waknaghatTime: "06:50 AM",
    toStation: "Solan Old Bus Stand",
    arrivalTime: "07:25 AM",
    fareFromWaknaghat: "₹35",
    fullFare: "₹75",
    timeOfDay: "morning",
    frequency: "Daily",
    routeVia: "Shimla ISBT ➔ Taradevi ➔ Shoghi ➔ Waknaghat Chowk ➔ Kandaghat ➔ Solan",
    keyStops: ["Shimla ISBT", "Taradevi", "Shoghi", "Waknaghat Chowk", "Kandaghat", "Solan"],
    note: "Early morning downhill service to Waknaghat and Solan.",
  },
  {
    id: "s2s-19",
    direction: "shimla_to_solan",
    operator: "Private Mudrika",
    busType: "Ordinary",
    fromStation: "Shimla Old Bus Stand",
    departureTime: "06:45 AM",
    waknaghatTime: "07:35 AM",
    toStation: "Solan Mall Road",
    arrivalTime: "08:15 AM",
    fareFromWaknaghat: "₹35",
    fullFare: "₹70",
    timeOfDay: "morning",
    frequency: "Daily",
    routeVia: "Cart Road ➔ Taradevi ➔ Waknaghat Chowk ➔ Kandaghat ➔ Solan",
    keyStops: ["Shimla Old", "Taradevi", "Waknaghat Chowk", "Kandaghat", "Solan"],
    note: "Convenient for morning arrivals to JUIT Waknaghat.",
  },
  {
    id: "s2s-20",
    direction: "shimla_to_solan",
    operator: "HRTC Express",
    busType: "Express",
    fromStation: "Shimla ISBT Tutikandi",
    departureTime: "07:30 AM",
    waknaghatTime: "08:15 AM",
    toStation: "Solan Old Bus Stand",
    arrivalTime: "08:50 AM",
    fareFromWaknaghat: "₹40",
    fullFare: "₹85",
    timeOfDay: "morning",
    frequency: "Daily",
    routeVia: "NH-5 Express Corridor via Waknaghat Chowk",
    keyStops: ["Shimla ISBT", "Taradevi", "Waknaghat Chowk", "Solan"],
    note: "Primary morning campus bus; ideal for 9:00 AM class arrivals.",
  },
  {
    id: "s2s-21",
    direction: "shimla_to_solan",
    operator: "HRTC Semi-Deluxe",
    busType: "Deluxe",
    fromStation: "Shimla ISBT Tutikandi",
    departureTime: "08:30 AM",
    waknaghatTime: "09:15 AM",
    toStation: "Solan Bypass / New Bus Stand",
    arrivalTime: "09:50 AM",
    fareFromWaknaghat: "₹50",
    fullFare: "₹105",
    timeOfDay: "morning",
    frequency: "Daily",
    routeVia: "Shimla ➔ Shoghi ➔ Waknaghat Chowk ➔ Kandaghat ➔ Solan",
    keyStops: ["Shimla ISBT", "Waknaghat Chowk", "Solan"],
  },
  {
    id: "s2s-22",
    direction: "shimla_to_solan",
    operator: "HRTC Himsuta Volvo",
    busType: "Volvo AC",
    fromStation: "Shimla ISBT Tutikandi",
    departureTime: "09:15 AM",
    waknaghatTime: "09:55 AM",
    toStation: "Solan Bypass",
    arrivalTime: "10:30 AM",
    fareFromWaknaghat: "₹110",
    fullFare: "₹220",
    timeOfDay: "morning",
    frequency: "Daily",
    routeVia: "NH-5 Corridor towards Chandigarh/Delhi",
    keyStops: ["Shimla ISBT", "Waknaghat Chowk", "Solan Bypass"],
    note: "AC Volvo departing Shimla for Chandigarh/Delhi.",
  },
  {
    id: "s2s-23",
    direction: "shimla_to_solan",
    operator: "HRTC Ordinary",
    busType: "Ordinary",
    fromStation: "Shimla Old Bus Stand",
    departureTime: "10:00 AM",
    waknaghatTime: "10:50 AM",
    toStation: "Solan Old Bus Stand",
    arrivalTime: "11:30 AM",
    fareFromWaknaghat: "₹35",
    fullFare: "₹75",
    timeOfDay: "morning",
    frequency: "Daily",
    routeVia: "Cart Road ➔ Taradevi ➔ Shoghi ➔ Waknaghat Chowk ➔ Kandaghat ➔ Solan",
    keyStops: ["Shimla Old", "Shoghi", "Waknaghat Chowk", "Kandaghat", "Solan"],
  },
  {
    id: "s2s-24",
    direction: "shimla_to_solan",
    operator: "Private Local Bus",
    busType: "Ordinary",
    fromStation: "Shimla ISBT Tutikandi",
    departureTime: "11:15 AM",
    waknaghatTime: "12:05 PM",
    toStation: "Solan Old Bus Stand",
    arrivalTime: "12:45 PM",
    fareFromWaknaghat: "₹35",
    fullFare: "₹75",
    timeOfDay: "morning",
    frequency: "Daily",
    routeVia: "Shimla ISBT ➔ Waknaghat Chowk ➔ Solan",
    keyStops: ["Shimla ISBT", "Waknaghat Chowk", "Kandaghat", "Solan"],
  },
  {
    id: "s2s-25",
    direction: "shimla_to_solan",
    operator: "HRTC Express",
    busType: "Express",
    fromStation: "Shimla ISBT Tutikandi",
    departureTime: "12:30 PM",
    waknaghatTime: "01:15 PM",
    toStation: "Solan New Bus Stand",
    arrivalTime: "01:50 PM",
    fareFromWaknaghat: "₹40",
    fullFare: "₹85",
    timeOfDay: "afternoon",
    frequency: "Daily",
    routeVia: "NH-5 Corridor via Waknaghat Chowk",
    keyStops: ["Shimla ISBT", "Taradevi", "Waknaghat Chowk", "Solan"],
  },
  {
    id: "s2s-26",
    direction: "shimla_to_solan",
    operator: "Private Mudrika",
    busType: "Ordinary",
    fromStation: "Shimla Old Bus Stand",
    departureTime: "01:45 PM",
    waknaghatTime: "02:35 PM",
    toStation: "Solan Old Bus Stand",
    arrivalTime: "03:15 PM",
    fareFromWaknaghat: "₹35",
    fullFare: "₹75",
    timeOfDay: "afternoon",
    frequency: "Daily",
    routeVia: "Cart Road ➔ Waknaghat Chowk ➔ Kandaghat ➔ Solan",
    keyStops: ["Shimla Old", "Waknaghat Chowk", "Kandaghat", "Solan"],
  },
  {
    id: "s2s-27",
    direction: "shimla_to_solan",
    operator: "HRTC Ordinary",
    busType: "Ordinary",
    fromStation: "Shimla ISBT Tutikandi",
    departureTime: "02:45 PM",
    waknaghatTime: "03:35 PM",
    toStation: "Solan Old Bus Stand",
    arrivalTime: "04:15 PM",
    fareFromWaknaghat: "₹35",
    fullFare: "₹75",
    timeOfDay: "afternoon",
    frequency: "Daily",
    routeVia: "Shimla ISBT ➔ Taradevi ➔ Waknaghat Chowk ➔ Kandaghat ➔ Solan",
    keyStops: ["Shimla ISBT", "Waknaghat Chowk", "Kandaghat", "Solan"],
  },
  {
    id: "s2s-28",
    direction: "shimla_to_solan",
    operator: "HRTC Express (Evening Prime)",
    busType: "Express",
    fromStation: "Shimla ISBT Tutikandi",
    departureTime: "03:45 PM",
    waknaghatTime: "04:30 PM",
    toStation: "Solan Old Bus Stand",
    arrivalTime: "05:10 PM",
    fareFromWaknaghat: "₹40",
    fullFare: "₹85",
    timeOfDay: "afternoon",
    frequency: "Daily",
    routeVia: "NH-5 Highway Corridor",
    keyStops: ["Shimla ISBT", "Taradevi", "Waknaghat Chowk", "Solan"],
    note: "High student ridership after evening class dismissals.",
  },
  {
    id: "s2s-29",
    direction: "shimla_to_solan",
    operator: "HRTC Semi-Deluxe",
    busType: "Deluxe",
    fromStation: "Shimla ISBT Tutikandi",
    departureTime: "04:45 PM",
    waknaghatTime: "05:30 PM",
    toStation: "Solan Bypass",
    arrivalTime: "06:10 PM",
    fareFromWaknaghat: "₹50",
    fullFare: "₹105",
    timeOfDay: "afternoon",
    frequency: "Daily",
    routeVia: "Shimla ➔ Waknaghat Chowk ➔ Kandaghat ➔ Solan",
    keyStops: ["Shimla ISBT", "Waknaghat Chowk", "Solan"],
  },
  {
    id: "s2s-30",
    direction: "shimla_to_solan",
    operator: "HRTC Ordinary",
    busType: "Ordinary",
    fromStation: "Shimla Old Bus Stand",
    departureTime: "05:30 PM",
    waknaghatTime: "06:20 PM",
    toStation: "Solan Old Bus Stand",
    arrivalTime: "07:05 PM",
    fareFromWaknaghat: "₹35",
    fullFare: "₹75",
    timeOfDay: "evening",
    frequency: "Daily",
    routeVia: "Cart Road ➔ Taradevi ➔ Waknaghat Chowk ➔ Kandaghat ➔ Solan",
    keyStops: ["Shimla Old", "Waknaghat Chowk", "Kandaghat", "Solan"],
  },
  {
    id: "s2s-31",
    direction: "shimla_to_solan",
    operator: "HRTC Himsuta Volvo",
    busType: "Volvo AC",
    fromStation: "Shimla ISBT Tutikandi",
    departureTime: "06:30 PM",
    waknaghatTime: "07:10 PM",
    toStation: "Solan Bypass",
    arrivalTime: "07:45 PM",
    fareFromWaknaghat: "₹110",
    fullFare: "₹220",
    timeOfDay: "evening",
    frequency: "Daily",
    routeVia: "NH-5 Express Corridor towards Delhi",
    keyStops: ["Shimla ISBT", "Waknaghat Chowk", "Solan Bypass"],
    note: "Evening AC Volvo service.",
  },
  {
    id: "s2s-32",
    direction: "shimla_to_solan",
    operator: "HRTC Ordinary",
    busType: "Ordinary",
    fromStation: "Shimla ISBT Tutikandi",
    departureTime: "07:30 PM",
    waknaghatTime: "08:20 PM",
    toStation: "Solan Old Bus Stand",
    arrivalTime: "09:00 PM",
    fareFromWaknaghat: "₹35",
    fullFare: "₹75",
    timeOfDay: "evening",
    frequency: "Daily",
    routeVia: "Shimla ISBT ➔ Waknaghat Chowk ➔ Kandaghat ➔ Solan",
    keyStops: ["Shimla ISBT", "Waknaghat Chowk", "Kandaghat", "Solan"],
  },
  {
    id: "s2s-33",
    direction: "shimla_to_solan",
    operator: "HRTC Ordinary (Last Regular to Solan)",
    busType: "Ordinary",
    fromStation: "Shimla ISBT Tutikandi",
    departureTime: "09:00 PM",
    waknaghatTime: "09:45 PM",
    toStation: "Solan Old Bus Stand",
    arrivalTime: "10:25 PM",
    fareFromWaknaghat: "₹40",
    fullFare: "₹80",
    timeOfDay: "evening",
    frequency: "Daily",
    routeVia: "Shimla ISBT ➔ Waknaghat Chowk ➔ Kandaghat ➔ Solan",
    keyStops: ["Shimla ISBT", "Waknaghat Chowk", "Kandaghat", "Solan"],
    note: "Last regular HRTC departure from Shimla ISBT to Solan.",
  },
];

export const TRANSIT_CONNECTIVITY_TIPS = [
  {
    title: "Waknaghat Chowk to JUIT Gate 1 (3.5 km Link Road)",
    detail: "Shared Maruti Omni cabs & autos ply continuously between Waknaghat Chowk (NH-5) and JUIT Gate 1. Fare is ₹30–₹40 per person on sharing, or ₹150–₹200 for full taxi reserve.",
    icon: "🛺",
  },
  {
    title: "HRTC Bus Frequency",
    detail: "Buses run on the Solan–Shimla NH-5 stretch every 10 to 15 minutes between 06:00 AM and 08:30 PM. All ordinary and express buses stop on wave at Waknaghat Chowk.",
    icon: "🚌",
  },
  {
    title: "Boarding Advice for Students",
    detail: "When boarding any Shimla or Solan bound bus from outside, tell the conductor 'Waknaghat Chowk JUIT Cut'. You can alight right at the campus arch gate.",
    icon: "🎫",
  },
  {
    title: "Toy Train Option (Kandaghat Station)",
    detail: "Kandaghat Railway Station (UNESCO Kalka-Shimla Toy Train) is 9 km south (15 mins drive). Take any Solan-bound bus to Kandaghat chowk.",
    icon: "🚂",
  },
];
