export interface FacultyMember {
  id: string;
  name: string;
  title: "Prof." | "Dr." | "Mr." | "Ms.";
  designation: string;
  department: string;
  deptKey: "cse" | "ece" | "maths" | "physics" | "civil" | "biotech" | "hss";
  email: string;
  phone?: string;
  mobile?: string;
  extension?: string;

  office?: string;
  areas: string[];
  timetableCode?: string;
  isHod?: boolean;
}

export const DEPARTMENTS = [
  { key: "all", label: "All Departments", count: 0 },
  { key: "cse", label: "CSE & IT", icon: "💻" },
  { key: "ece", label: "ECE", icon: "📡" },
  { key: "maths", label: "Mathematics", icon: "📐" },
  { key: "physics", label: "Physics", icon: "⚛️" },
  { key: "civil", label: "Civil Engg", icon: "🏗️" },
  { key: "biotech", label: "Biotechnology", icon: "🧬" },
  { key: "hss", label: "HSS & Mgmt", icon: "📚" },
] as const;

export const FACULTY_MEMBERS: FacultyMember[] = [
  // ══════════════════════════════════════════════════════════════════════
  // COMPUTER SCIENCE & ENGINEERING AND IT (CSE & IT)
  // ══════════════════════════════════════════════════════════════════════
  {
    id: "cse-vks",
    name: "Dr. Vivek Kumar Sehgal",
    title: "Prof.",
    designation: "Professor & Head (Emerging Tech)",
    department: "Computer Science & Engineering and IT",
    deptKey: "cse",
    email: "vivek.sehgal@juit.ac.in",
    phone: "+91-1792-239281",
    office: "Academic Block, Room 122",
    areas: ["IoT", "Cloud Computing", "Computer Networks", "Cyber Security"],
    timetableCode: "VKS",
    isHod: true,
  },
  {
    id: "cse-pkg",
    name: "Dr. Pradeep Kumar Gupta",
    title: "Prof.",
    designation: "Professor & Head (Core Computing)",
    department: "Computer Science & Engineering and IT",
    deptKey: "cse",
    email: "pradeepkumar.gupta@juitsolan.in",
    phone: "+91-1792-239276",
    office: "Academic Block, Room 124",
    areas: ["Software Engineering", "Cloud Computing", "Information Security"],
    timetableCode: "PKG",
    isHod: true,
  },
  {
    id: "cse-pk",
    name: "Dr. Pardeep Kumar",
    title: "Dr.",
    designation: "Associate Professor",
    department: "Computer Science & Engineering and IT",
    deptKey: "cse",
    email: "pardeep.kumar@juit.ac.in",
    phone: "+91-1792-239268",
    office: "Academic Block, Room 118",
    areas: ["Data Mining", "Machine Learning", "Big Data Analytics"],
    timetableCode: "PK",
  },
  {
    id: "cse-rb",
    name: "Dr. Ravindara Bhatt",
    title: "Dr.",
    designation: "Associate Professor",
    department: "Computer Science & Engineering and IT",
    deptKey: "cse",
    email: "ravindara.bhatt@juit.ac.in",
    phone: "+91-1792-239271",
    office: "Academic Block, Room 116",
    areas: ["Image Processing", "Computer Vision", "Pattern Recognition"],
    timetableCode: "RB",
  },
  {
    id: "cse-yk",
    name: "Dr. Yugal Kumar",
    title: "Dr.",
    designation: "Associate Professor",
    department: "Computer Science & Engineering and IT",
    deptKey: "cse",
    email: "yugal.kumar@juit.ac.in",
    phone: "+91-1792-239284",
    office: "Academic Block, Room 114",
    areas: ["Swarm Intelligence", "Soft Computing", "Machine Learning", "Bioinformatics"],
    timetableCode: "YK",
  },
  {
    id: "cse-eg",
    name: "Dr. Ekta Gandotra",
    title: "Dr.",
    designation: "Associate Professor",
    department: "Computer Science & Engineering and IT",
    deptKey: "cse",
    email: "ekta.gandotra@juit.ac.in",
    phone: "+91-1792-239287",
    office: "Academic Block, Room 112",
    areas: ["Information Security", "Malware Analysis", "Machine Learning"],
    timetableCode: "EG",
  },
  {
    id: "cse-as",
    name: "Dr. Aman Sharma",
    title: "Dr.",
    designation: "Assistant Professor (Senior Grade)",
    department: "Computer Science & Engineering and IT",
    deptKey: "cse",
    email: "aman.sharma@juit.ac.in",
    phone: "+91-1792-239290",
    office: "Academic Block, Room 204",
    areas: ["Deep Learning", "Natural Language Processing", "AI Applications"],
    timetableCode: "AMS",
  },
  {
    id: "cse-hs",
    name: "Dr. Hari Singh",
    title: "Dr.",
    designation: "Assistant Professor (Senior Grade)",
    department: "Computer Science & Engineering and IT",
    deptKey: "cse",
    email: "hari.singh@juit.ac.in",
    phone: "+91-1792-239293",
    office: "Academic Block, Room 206",
    areas: ["Software Testing", "Agile Methodologies", "Defect Prediction"],
    timetableCode: "HS",
  },
  {
    id: "cse-ak",
    name: "Dr. Amit Kumar",
    title: "Dr.",
    designation: "Assistant Professor (Senior Grade)",
    department: "Computer Science & Engineering and IT",
    deptKey: "cse",
    email: "amit.kumar@juit.ac.in",
    phone: "+91-1792-239295",
    office: "Academic Block, Room 208",
    areas: ["Database Systems", "Big Data", "Distributed Computing"],
    timetableCode: "AK",
  },
  {
    id: "cse-pd",
    name: "Dr. Pankaj Dhiman",
    title: "Dr.",
    designation: "Assistant Professor (Senior Grade)",
    department: "Computer Science & Engineering and IT",
    deptKey: "cse",
    email: "pankaj.dhiman@juit.ac.in",
    phone: "+91-1792-239297",
    office: "Academic Block, Room 210",
    areas: ["Computer Networks", "Mobile Computing", "Wireless Sensor Networks"],
    timetableCode: "PD",
  },
  {
    id: "cse-ns",
    name: "Dr. Nishant Sharma",
    title: "Dr.",
    designation: "Assistant Professor (Senior Grade)",
    department: "Computer Science & Engineering and IT",
    deptKey: "cse",
    email: "nishant.sharma@juit.ac.in",
    phone: "+91-1792-239299",
    office: "Academic Block, Room 212",
    areas: ["Data Structures & Algorithms", "Theory of Computation", "Graph Theory"],
    timetableCode: "NS",
  },
  {
    id: "cse-ark",
    name: "Dr. Arvind Kumar",
    title: "Dr.",
    designation: "Assistant Professor (Senior Grade)",
    department: "Computer Science & Engineering and IT",
    deptKey: "cse",
    email: "arvind.kumar@juit.ac.in",
    phone: "+91-1792-239301",
    office: "Academic Block, Room 214",
    areas: ["Computer Vision", "Medical Imaging", "Deep Learning"],
    timetableCode: "ARK",
  },
  {
    id: "cse-ff",
    name: "Mr. Faisal Firdous",
    title: "Mr.",
    designation: "Assistant Professor (Grade-I) & Hostel Warden",
    department: "Computer Science & Engineering and IT",
    deptKey: "cse",
    email: "faisal.firdous@juitsolan.in",
    phone: "+91-1792-239302",
    mobile: "6005636085",
    office: "Academic Block / Boys Hostel Warden Office",
    areas: [
      "Software Development Fundamentals",
      "Artificial Intelligence & Machine Learning",
      "Deep Learning",
      "Computer Vision",
      "Blockchain & Cryptography",
      "Data Structures & Algorithms",
    ],
    timetableCode: "FSL",
  },

  // ══════════════════════════════════════════════════════════════════════
  // ELECTRONICS AND COMMUNICATION ENGINEERING (ECE)

  // ══════════════════════════════════════════════════════════════════════
  {
    id: "ece-sp",
    name: "Dr. Shweta Pandit",
    title: "Dr.",
    designation: "Associate Professor & Head",
    department: "Electronics and Communication Engineering",
    deptKey: "ece",
    email: "shweta.pandit@juit.ac.in",
    phone: "+91-1792-239250",
    office: "Academic Block, Room 104",
    areas: ["Wireless Communication", "Signal Processing", "5G/6G Networks"],
    timetableCode: "SP",
    isHod: true,
  },
  {
    id: "ece-rk",
    name: "Dr. Rajiv Kumar",
    title: "Prof.",
    designation: "Professor",
    department: "Electronics and Communication Engineering",
    deptKey: "ece",
    email: "rajiv.kumar@juit.ac.in",
    phone: "+91-1792-239252",
    office: "Academic Block, Room 102",
    areas: ["Digital Communication", "Information Theory", "OFDM Systems"],
    timetableCode: "RK",
  },
  {
    id: "ece-sj",
    name: "Dr. Shruti Jain",
    title: "Prof.",
    designation: "Professor & Associate Dean (Innovation)",
    department: "Electronics and Communication Engineering",
    deptKey: "ece",
    email: "shruti.jain@juit.ac.in",
    phone: "+91-1792-239255",
    office: "Academic Block, Room 106",
    areas: ["Biomedical Image Processing", "VLSI Design", "Bio-Signal Analysis"],
    timetableCode: "SJ",
  },
  {
    id: "ece-hs",
    name: "Dr. Harsh Sohal",
    title: "Dr.",
    designation: "Associate Professor",
    department: "Electronics and Communication Engineering",
    deptKey: "ece",
    email: "harsh.sohal@juit.ac.in",
    phone: "+91-1792-239258",
    office: "Academic Block, Room 108",
    areas: ["Embedded Systems", "IoT Devices", "Digital System Design", "Microcontrollers"],
    timetableCode: "HSL",
  },
  {
    id: "ece-vb",
    name: "Dr. Vikas Baghel",
    title: "Dr.",
    designation: "Associate Professor",
    department: "Electronics and Communication Engineering",
    deptKey: "ece",
    email: "vikas.baghel@juit.ac.in",
    phone: "+91-1792-239260",
    office: "Academic Block, Room 110",
    areas: ["Antenna Design", "Microwave Engineering", "Metamaterials"],
    timetableCode: "VB",
  },
  {
    id: "ece-ep",
    name: "Dr. Emjee Puthooran",
    title: "Dr.",
    designation: "Assistant Professor (Senior Grade)",
    department: "Electronics and Communication Engineering",
    deptKey: "ece",
    email: "emjee.puthooran@juit.ac.in",
    phone: "+91-1792-239262",
    office: "Academic Block, Room 113",
    areas: ["VLSI Architectures", "Digital Signal Processing", "FPGA Design"],
    timetableCode: "EP",
  },
  {
    id: "ece-ak",
    name: "Dr. Alok Kumar",
    title: "Dr.",
    designation: "Assistant Professor (Senior Grade)",
    department: "Electronics and Communication Engineering",
    deptKey: "ece",
    email: "alok.kumar@juit.ac.in",
    phone: "+91-1792-239265",
    office: "Academic Block, Room 115",
    areas: ["Optical Communication", "Photonic Devices", "Fiber Optics"],
    timetableCode: "ALOK",
  },
  {
    id: "ece-pg",
    name: "Dr. Pardeep Garg",
    title: "Dr.",
    designation: "Assistant Professor (Senior Grade)",
    department: "Electronics and Communication Engineering",
    deptKey: "ece",
    email: "pardeep.garg@juit.ac.in",
    phone: "+91-1792-239267",
    office: "Academic Block, Room 117",
    areas: ["Semiconductor Devices", "Nanoelectronics", "Low Power VLSI"],
    timetableCode: "PG",
  },

  // ══════════════════════════════════════════════════════════════════════
  // MATHEMATICS
  // ══════════════════════════════════════════════════════════════════════
  {
    id: "mat-rkb",
    name: "Dr. Rakesh Kumar Bajaj",
    title: "Prof.",
    designation: "Professor & Head",
    department: "Mathematics",
    deptKey: "maths",
    email: "rakesh.bajaj@juit.ac.in",
    phone: "+91-1792-239230",
    office: "Academic Block, Room 220",
    areas: ["Fuzzy Sets", "Decision Making", "Information Measures", "Soft Computing"],
    timetableCode: "RKB",
    isHod: true,
  },
  {
    id: "mat-rsr",
    name: "Dr. R.S. Raja Durai",
    title: "Prof.",
    designation: "Professor",
    department: "Mathematics",
    deptKey: "maths",
    email: "rs.rajadurai@juit.ac.in",
    phone: "+91-1792-239232",
    office: "Academic Block, Room 222",
    areas: ["Cryptography", "Number Theory", "Algebraic Coding Theory"],
    timetableCode: "RSR",
  },
  {
    id: "mat-nk",
    name: "Dr. Neel Kanth",
    title: "Dr.",
    designation: "Associate Professor",
    department: "Mathematics",
    deptKey: "maths",
    email: "neel.kanth@juit.ac.in",
    phone: "+91-1792-239234",
    office: "Academic Block, Room 224",
    areas: ["Differential Equations", "Numerical Analysis", "Mathematical Modelling"],
    timetableCode: "NK",
  },
  {
    id: "mat-pkp",
    name: "Dr. Pradeep Kumar Pandey",
    title: "Dr.",
    designation: "Associate Professor",
    department: "Mathematics",
    deptKey: "maths",
    email: "pradeep.pandey@juit.ac.in",
    phone: "+91-1792-239236",
    office: "Academic Block, Room 226",
    areas: ["Numerical Solutions of ODEs/PDEs", "Applied Mathematics"],
    timetableCode: "PKP",
  },
  {
    id: "mat-mds",
    name: "Dr. Mandeep Singh",
    title: "Dr.",
    designation: "Assistant Professor (Senior Grade)",
    department: "Mathematics",
    deptKey: "maths",
    email: "mandeep.singh@juit.ac.in",
    phone: "+91-1792-239238",
    office: "Academic Block, Room 228",
    areas: ["Complex Analysis", "Geometric Function Theory", "Linear Algebra"],
    timetableCode: "MDS",
  },
  {
    id: "mat-bkp",
    name: "Dr. Bhupendra Kumar Pathak",
    title: "Dr.",
    designation: "Assistant Professor (Senior Grade)",
    department: "Mathematics",
    deptKey: "maths",
    email: "bhupendra.pathak@juit.ac.in",
    phone: "+91-1792-239240",
    office: "Academic Block, Room 230",
    areas: ["Probability & Statistics", "Reliability Theory", "Stochastic Modeling"],
    timetableCode: "BKP",
  },
  {
    id: "mat-ss",
    name: "Dr. Saurabh Srivastava",
    title: "Dr.",
    designation: "Assistant Professor (Senior Grade)",
    department: "Mathematics",
    deptKey: "maths",
    email: "saurabh.srivastava@juit.ac.in",
    phone: "+91-1792-239242",
    office: "Academic Block, Room 232",
    areas: ["Operations Research", "Optimization Techniques", "Mathematical Finance"],
    timetableCode: "SS",
  },

  // ══════════════════════════════════════════════════════════════════════
  // PHYSICS AND MATERIALS SCIENCE
  // ══════════════════════════════════════════════════════════════════════
  {
    id: "phy-pbb",
    name: "Dr. P.B. Barman",
    title: "Prof.",
    designation: "Professor & Head",
    department: "Physics and Materials Science",
    deptKey: "physics",
    email: "pb.barman@juit.ac.in",
    phone: "+91-1792-239201",
    office: "Academic Block, Room 301",
    areas: ["Chalcogenide Glasses", "Amorphous Semiconductors", "Materials Science"],
    timetableCode: "PBB",
    isHod: true,
  },
  {
    id: "phy-skk",
    name: "Dr. Sunil Kumar Khah",
    title: "Prof.",
    designation: "Professor",
    department: "Physics and Materials Science",
    deptKey: "physics",
    email: "sunilkumar.khah@juit.ac.in",
    phone: "+91-1792-239203",
    office: "Academic Block, Room 303",
    areas: ["Thin Film Solar Cells", "Renewable Energy", "Photovoltaics"],
    timetableCode: "SKK",
  },
  {
    id: "phy-vs",
    name: "Dr. Vineet Sharma",
    title: "Prof.",
    designation: "Professor",
    department: "Physics and Materials Science",
    deptKey: "physics",
    email: "vineet.sharma@juit.ac.in",
    phone: "+91-1792-239205",
    office: "Academic Block, Room 305",
    areas: ["Solid State Ionics", "Polymer Electrolytes", "Battery Technology"],
    timetableCode: "VS",
  },
  {
    id: "phy-rrs",
    name: "Dr. Ragini Raj Singh",
    title: "Dr.",
    designation: "Associate Professor",
    department: "Physics and Materials Science",
    deptKey: "physics",
    email: "raginiraj.singh@juit.ac.in",
    phone: "+91-1792-239207",
    office: "Academic Block, Room 307",
    areas: ["Nanotechnology", "Ferrites", "Gas Sensors", "Magnetic Materials"],
    timetableCode: "RRS",
  },
  {
    id: "phy-skh",
    name: "Dr. Surajit Kumar Hazra",
    title: "Dr.",
    designation: "Associate Professor",
    department: "Physics and Materials Science",
    deptKey: "physics",
    email: "surajit.hazra@juit.ac.in",
    phone: "+91-1792-239209",
    office: "Academic Block, Room 309",
    areas: ["Condensed Matter Physics", "Superconductivity", "Quantum Mechanics"],
    timetableCode: "HAZ",
  },
  {
    id: "phy-skt",
    name: "Dr. Sanjiv Kumar Tiwari",
    title: "Dr.",
    designation: "Assistant Professor (Senior Grade)",
    department: "Physics and Materials Science",
    deptKey: "physics",
    email: "sanjiv.tiwari@juit.ac.in",
    phone: "+91-1792-239211",
    office: "Academic Block, Room 311",
    areas: ["Electromagnetic Theory", "Plasma Physics", "Optics"],
    timetableCode: "SKT",
  },

  // ══════════════════════════════════════════════════════════════════════
  // CIVIL ENGINEERING
  // ══════════════════════════════════════════════════════════════════════
  {
    id: "civ-ak",
    name: "Dr. Ashish Kumar",
    title: "Prof.",
    designation: "Professor & Head",
    department: "Civil Engineering",
    deptKey: "civil",
    email: "ashish.kumar@juit.ac.in",
    phone: "+91-1792-239330",
    office: "Civil Block (Lower Terrace), Room C101",
    areas: ["Structural Engineering", "Earthquake Engineering", "Concrete Technology"],
    timetableCode: "AK_CIV",
    isHod: true,
  },
  {
    id: "civ-akg",
    name: "Dr. Ashok Kumar Gupta",
    title: "Prof.",
    designation: "Professor & Dean (Academics)",
    department: "Civil Engineering",
    deptKey: "civil",
    email: "ashok.gupta@juit.ac.in",
    phone: "+91-1792-239332",
    office: "Admin Block / Civil Wing, Room C103",
    areas: ["Environmental Engineering", "Water Resources", "Waste Management"],
    timetableCode: "AKG",
  },
  {
    id: "civ-ad",
    name: "Dr. Amardeep",
    title: "Dr.",
    designation: "Associate Professor",
    department: "Civil Engineering",
    deptKey: "civil",
    email: "amardeep@juit.ac.in",
    phone: "+91-1792-239335",
    office: "Civil Block, Room C105",
    areas: ["Geotechnical Engineering", "Slope Stability", "Soil Mechanics"],
    timetableCode: "AD",
  },
  {
    id: "civ-nsp",
    name: "Dr. Niraj Singh Parihar",
    title: "Dr.",
    designation: "Assistant Professor (Senior Grade)",
    department: "Civil Engineering",
    deptKey: "civil",
    email: "niraj.parihar@juit.ac.in",
    phone: "+91-1792-239338",
    office: "Civil Block, Room C107",
    areas: ["Transportation Engineering", "Highway Materials", "Traffic Flow"],
    timetableCode: "NSP",
  },
  {
    id: "civ-rr",
    name: "Dr. Rishi Rana",
    title: "Dr.",
    designation: "Assistant Professor (Senior Grade)",
    department: "Civil Engineering",
    deptKey: "civil",
    email: "rishi.rana@juit.ac.in",
    phone: "+91-1792-239340",
    office: "Civil Block, Room C109",
    areas: ["Structural Health Monitoring", "Bridge Engineering", "Finite Element Analysis"],
    timetableCode: "RR",
  },
  {
    id: "civ-tg",
    name: "Dr. Tanmay Gupta",
    title: "Dr.",
    designation: "Assistant Professor (Senior Grade)",
    department: "Civil Engineering",
    deptKey: "civil",
    email: "tanmay.gupta@juit.ac.in",
    phone: "+91-1792-239342",
    office: "Civil Block, Room C111",
    areas: ["GIS & Remote Sensing", "Surveying", "Urban Hydrology"],
    timetableCode: "TG",
  },

  // ══════════════════════════════════════════════════════════════════════
  // BIOTECHNOLOGY AND BIOINFORMATICS
  // ══════════════════════════════════════════════════════════════════════
  {
    id: "bt-js",
    name: "Dr. Jata Shankar",
    title: "Prof.",
    designation: "Professor & Head",
    department: "Biotechnology and Bioinformatics",
    deptKey: "biotech",
    email: "jata.shankar@juit.ac.in",
    phone: "+91-1792-239215",
    office: "Bio Block, Room B101",
    areas: ["Microbiology", "Infectious Diseases", "Fungal Pathogenesis", "Immunology"],
    timetableCode: "JS",
    isHod: true,
  },
  {
    id: "bt-sk",
    name: "Dr. Sudhir Kumar",
    title: "Prof.",
    designation: "Professor & Dean (Research & Internationalization)",
    department: "Biotechnology and Bioinformatics",
    deptKey: "biotech",
    email: "sudhir.kumar@juit.ac.in",
    phone: "+91-1792-239217",
    office: "Bio Block, Room B103",
    areas: ["Industrial Biotechnology", "Bioprocess Engineering", "Biofuels"],
    timetableCode: "SK",
  },
  {
    id: "bt-trs",
    name: "Dr. Tiratha Raj Singh",
    title: "Prof.",
    designation: "Professor & Associate Dean",
    department: "Biotechnology and Bioinformatics",
    deptKey: "biotech",
    email: "tiratharaj.singh@juit.ac.in",
    phone: "+91-1792-239219",
    office: "Bio Block, Room B105",
    areas: ["Computational Biology", "Bioinformatics", "Genomics", "NGS Data Analysis"],
    timetableCode: "TRS",
  },
  {
    id: "bt-hs",
    name: "Dr. Hemant Sood",
    title: "Prof.",
    designation: "Professor",
    department: "Biotechnology and Bioinformatics",
    deptKey: "biotech",
    email: "hemant.sood@juit.ac.in",
    phone: "+91-1792-239221",
    office: "Bio Block, Room B107",
    areas: ["Plant Biotechnology", "Medicinal Plants", "Tissue Culture", "Phytochemistry"],
    timetableCode: "HSOOD",
  },
  {
    id: "bt-jv",
    name: "Dr. Jitendraa Vashistt",
    title: "Dr.",
    designation: "Associate Professor",
    department: "Biotechnology and Bioinformatics",
    deptKey: "biotech",
    email: "jitendraa.vashistt@juit.ac.in",
    phone: "+91-1792-239223",
    office: "Bio Block, Room B109",
    areas: ["Proteomics", "Antimicrobial Resistance", "Molecular Diagnostics"],
    timetableCode: "JV",
  },
  {
    id: "bt-akn",
    name: "Dr. Ashok Kumar Nadda",
    title: "Dr.",
    designation: "Associate Professor",
    department: "Biotechnology and Bioinformatics",
    deptKey: "biotech",
    email: "ashok.nadda@juit.ac.in",
    phone: "+91-1792-239225",
    office: "Bio Block, Room B111",
    areas: ["Biocatalysis", "Enzyme Technology", "Waste Valorization", "Biomaterials"],
    timetableCode: "AKN",
  },

  // ══════════════════════════════════════════════════════════════════════
  // HUMANITIES & SOCIAL SCIENCES (HSS) & JAYPEE BUSINESS SCHOOL (JBSW)
  // ══════════════════════════════════════════════════════════════════════
  {
    id: "hss-ak",
    name: "Dr. Anupriya Kaur",
    title: "Prof.",
    designation: "Professor & Head",
    department: "Humanities and Social Sciences",
    deptKey: "hss",
    email: "anupriya.kaur@juit.ac.in",
    phone: "+91-1792-239310",
    office: "Academic Block, Room 215",
    areas: ["Marketing Management", "Consumer Behavior", "Service Marketing"],
    timetableCode: "AK_HSS",
    isHod: true,
  },
  {
    id: "hss-as",
    name: "Dr. Amit Srivastava",
    title: "Prof.",
    designation: "Professor & Head (JBSW)",
    department: "Humanities, Social Sciences & Management",
    deptKey: "hss",
    email: "amit.srivastava@juit.ac.in",
    phone: "+91-1792-239312",
    office: "Academic Block, Room 217",
    areas: ["Financial Management", "Corporate Finance", "Accounting", "Economics"],
    timetableCode: "AS_HSS",
    isHod: true,
  },
  {
    id: "hss-ts",
    name: "Dr. Tanu Sharma",
    title: "Dr.",
    designation: "Associate Professor",
    department: "Humanities and Social Sciences",
    deptKey: "hss",
    email: "tanu.sharma@juit.ac.in",
    phone: "+91-1792-239314",
    office: "Academic Block, Room 219",
    areas: ["Human Resource Management", "Organizational Behavior", "Communication Skills"],
    timetableCode: "TS",
  },
  {
    id: "hss-ds",
    name: "Dr. Deler Singh",
    title: "Dr.",
    designation: "Assistant Professor",
    department: "Humanities and Social Sciences",
    deptKey: "hss",
    email: "deler.singh@juit.ac.in",
    phone: "+91-1792-239316",
    office: "Academic Block, Room 221",
    areas: ["English Literature", "Business Communication", "Soft Skills", "Professional Ethics"],
    timetableCode: "DLR",
  },
  {
    id: "hss-tg",
    name: "Triambica Gautam",
    title: "Ms.",
    designation: "Assistant Professor (Grade-II)",
    department: "Humanities and Social Sciences",
    deptKey: "hss",
    email: "triambica.gautam@juit.ac.in",
    phone: "+91-1792-239318",
    office: "Academic Block, Room 223",
    areas: ["English Language & Linguistics", "Technical Writing", "Corporate Communication"],
    timetableCode: "TG_HSS",
  },
  {
    id: "hss-ac",
    name: "Dr. Abhilasha Chauhan",
    title: "Dr.",
    designation: "Assistant Professor (Grade-II)",
    department: "Humanities and Social Sciences",
    deptKey: "hss",
    email: "abhilasha.chauhan@juit.ac.in",
    phone: "+91-1792-239320",
    office: "Academic Block, Room 225",
    areas: ["Economics", "Managerial Economics", "Macroeconomics", "Sustainable Development"],
    timetableCode: "AC",
  },
  {
    id: "hss-nj",
    name: "Dr. Neena Jindal",
    title: "Dr.",
    designation: "Assistant Professor",
    department: "Humanities and Social Sciences",
    deptKey: "hss",
    email: "neena.jindal@juit.ac.in",
    phone: "+91-1792-239322",
    office: "Academic Block, Room 227",
    areas: ["Universal Human Values (UHV)", "Professional Ethics", "Philosophy"],
    timetableCode: "NJL",
  },
];
