export type JuitLinkCategory =
  | "all"
  | "library"
  | "academic"
  | "career"
  | "campus_services"
  | "student_bodies";

export interface JuitLinkItem {
  id: string;
  title: string;
  description: string;
  url: string;
  category: "library" | "academic" | "career" | "campus_services" | "student_bodies";
  badge?: string;
  icon: string;
  isPrimary?: boolean;
  tags: string[];
}

export interface JuitContactItem {
  id: string;
  role: string;
  department?: string;
  email?: string;
  phone?: string;
  location?: string;
  timing?: string;
  isEmergency?: boolean;
  category?: "emergency" | "administration" | "health_hostel" | "police_safety";
  priority?: number;
}

export const JUIT_CATEGORIES: { id: JuitLinkCategory; label: string; icon: string }[] = [
  { id: "all", label: "All Links", icon: "🌐" },
  { id: "library", label: "Library & LRC", icon: "📚" },
  { id: "academic", label: "Academic & ERP", icon: "🎓" },
  { id: "career", label: "Placement & Alumni", icon: "💼" },
  { id: "campus_services", label: "Services & Fees", icon: "🏢" },
  { id: "student_bodies", label: "Clubs & Bodies", icon: "🎭" },
];

export const JUIT_OFFICIAL_LINKS: JuitLinkItem[] = [
  // ─── 📚 LIBRARY & LEARNING RESOURCE CENTRE (LRC) ───────────────────────────
  {
    id: "lrc-main",
    title: "Learning Resource Centre (LRC)",
    description: "Central library portal with access to 50,000+ volumes, opening hours, borrowing rules and announcements.",
    url: "https://www.juit.ac.in/lrc/home.php",
    category: "library",
    badge: "Official LRC",
    icon: "📚",
    isPrimary: true,
    tags: ["library", "lrc", "books", "central library", "circulation", "reading room"],
  },
  {
    id: "web-opac",
    title: "Web OPAC (Koha Catalog)",
    description: "Search 24/7 for available books, journals, CDs, thesis reports, check due dates, and manage book renewals.",
    url: "https://www.juit.ac.in/lrc/home.php",
    category: "library",
    badge: "Book Search",
    icon: "🔍",
    isPrimary: true,
    tags: ["opac", "koha", "book search", "catalogue", "borrowing", "due dates"],
  },
  {
    id: "remotexs",
    title: "RemoteXs (Off-Campus Library Access)",
    description: "Seamless single-sign-on remote access to subscribed e-journals, research databases and IEEE Xplore outside campus.",
    url: "https://www.juit.ac.in/lrc/home.php",
    category: "library",
    badge: "Remote Access",
    icon: "🌐",
    isPrimary: true,
    tags: ["remotexs", "remote", "off-campus", "e-resources", "vpn", "journals"],
  },
  {
    id: "dspace-ir",
    title: "Institutional Repository (DSpace)",
    description: "Digital archive of faculty publications, research papers, M.Tech/Ph.D. theses, and student project dissertations.",
    url: "http://www.ir.juit.ac.in:8080/jspui/",
    category: "library",
    badge: "Digital Archive",
    icon: "📂",
    tags: ["dspace", "repository", "theses", "dissertations", "research papers", "faculty publications"],
  },
  {
    id: "past-papers",
    title: "Previous Years Question Papers",
    description: "Archive of past mid-sem (T1, T2) and end-sem (T3) question papers across all engineering branches and semesters.",
    url: "http://www.ir.juit.ac.in:8080/jspui/handle/123456789/22",
    category: "library",
    badge: "Past Papers",
    icon: "📝",
    isPrimary: true,
    tags: ["question papers", "past papers", "pyq", "exams", "previous year", "t1", "t2", "t3"],
  },
  {
    id: "e-resources",
    title: "E-Resources & Subscribed Databases",
    description: "Access premium academic databases including IEEE Xplore, ScienceDirect, Springer, ACM DL, and ASCE.",
    url: "https://www.juit.ac.in/lrc/home.php",
    category: "library",
    badge: "Databases",
    icon: "📑",
    tags: ["ieee", "sciencedirect", "springer", "acm", "journals", "e-books", "databases"],
  },
  {
    id: "ndli",
    title: "National Digital Library of India (NDLI)",
    description: "Federated national portal sponsored by MHRD with millions of digital books, video lectures and educational resources.",
    url: "https://ndl.iitkgp.ac.in/",
    category: "library",
    badge: "NDLI Portal",
    icon: "🇮🇳",
    tags: ["ndli", "national digital library", "iit kharagpur", "mhrd", "books"],
  },

  // ─── 🎓 ACADEMIC & ERP PORTALS ─────────────────────────────────────────────
  {
    id: "web-portal",
    title: "Campus Lynx / Web Portal (ERP)",
    description: "Official student ERP for checking live class attendance percentage, SGPA/CGPA results, semester grades and fee receipts.",
    url: "https://webportal.juit.ac.in:6011/studentportal/",
    category: "academic",
    badge: "Attendance & Grades",
    icon: "🌐",
    isPrimary: true,
    tags: ["webportal", "web portal", "lynx", "campus lynx", "attendance", "cgpa", "sgpa", "grades", "results", "erp"],
  },
  {
    id: "lms-moodle",
    title: "JUIT LMS (Moodle)",
    description: "Course management system for teacher lecture slides, assignment submissions, coding lab manuals and course quizzes.",
    url: "https://lms.juit.ac.in/login/index.php",
    category: "academic",
    badge: "Course Moodle",
    icon: "🎓",
    isPrimary: true,
    tags: ["lms", "moodle", "assignments", "course materials", "notes", "slides", "quizzes"],
  },
  {
    id: "juit-home",
    title: "Official JUIT Solan Website",
    description: "Main university homepage with academic circulars, latest notices, admissions, announcements and departmental portals.",
    url: "https://www.juit.ac.in/",
    category: "academic",
    badge: "University Portal",
    icon: "🏛️",
    isPrimary: true,
    tags: ["website", "main", "official", "university", "notices", "announcements"],
  },
  {
    id: "examination-cell",
    title: "Examination & Evaluation Cell",
    description: "Rules for grade points, criteria for SGPA/CGPA calculation, backlog examinations, answer sheet scrutiny and degree transcripts.",
    url: "https://www.juit.ac.in/academic-calendar",
    category: "academic",
    badge: "Exam Cell",
    icon: "📊",
    tags: ["exams", "examination", "results", "grading", "evaluation", "transcripts", "cgpa"],
  },
  {
    id: "academic-calendar",
    title: "Academic Calendars & Guidelines",
    description: "Official calendar for Odd/Even semesters containing semester start dates, T1/T2/T3 exams, holidays and student vacations.",
    url: "https://www.juit.ac.in/academic-calendar",
    category: "academic",
    badge: "Calendar",
    icon: "🗓️",
    tags: ["calendar", "academic calendar", "semester schedule", "holidays", "vacations"],
  },
  {
    id: "curriculum-syllabus",
    title: "Curriculum & Course Structure",
    description: "Approved syllabus regulations, credit distribution, and semester-wise course structures for all undergraduate and postgraduate programs.",
    url: "https://www.juit.ac.in/coursescurriculum",
    category: "academic",
    badge: "Curriculum",
    icon: "📚",
    tags: ["curriculum", "syllabus", "btech", "course structure", "credits", "electives"],
  },

  // ─── 💼 PLACEMENT, ALUMNI & CAREERS ───────────────────────────────────────
  {
    id: "placement-cell",
    title: "Training & Placement Cell (T&P)",
    description: "Campus recruitment records, participating corporate recruiters, internship guidelines, and placement policy.",
    url: "https://www.juit.ac.in/placement/",
    category: "career",
    badge: "Placements",
    icon: "💼",
    isPrimary: true,
    tags: ["placement", "t&p", "training and placement", "jobs", "internships", "recruiters", "packages"],
  },
  {
    id: "alumni-network",
    title: "JUIT Alumni Association & Network",
    description: "Global alumni network connecting 10,000+ graduates for mentorship, career advice, and annual alumni reunions.",
    url: "https://www.juit.ac.in/alumni/",
    category: "career",
    badge: "Alumni Network",
    icon: "🤝",
    tags: ["alumni", "graduates", "network", "mentorship", "alumni portal"],
  },
  {
    id: "tiedc-incubator",
    title: "TIEDC (Incubation & Entrepreneurship)",
    description: "Technology Incubation and Entrepreneurship Development Cell fostering student startups, seed grants and patent filings.",
    url: "https://tiedc.in/",
    category: "career",
    badge: "Startup Cell",
    icon: "💡",
    tags: ["tiedc", "incubation", "startup", "entrepreneurship", "funding", "patents"],
  },

  // ─── 🏢 CAMPUS SERVICES, FEES & STUDENT WELFARE ────────────────────────────
  {
    id: "fee-payment",
    title: "Online Fee Payment Portal",
    description: "Secure gateway for online payment of semester academic fees, hostel accommodation fees, and fine dues.",
    url: "https://webportal.juit.ac.in:6011/studentportal/",
    category: "campus_services",
    badge: "Fee Payment",
    icon: "💳",
    isPrimary: true,
    tags: ["fee", "fees", "fee payment", "tuition", "hostel fee", "payment gateway"],
  },
  {
    id: "hostels-mess",
    title: "Hostels & Annapurna Mess Facilities",
    description: "Hostel wardens, room amenities, curfew policies, Annapurna dining hall rules, and mess management committees.",
    url: "https://www.juit.ac.in/",
    category: "campus_services",
    badge: "Hostels & Mess",
    icon: "🏢",
    tags: ["hostel", "mess", "annapurna", "rooms", "accommodation", "warden"],
  },
  {
    id: "anti-ragging",
    title: "Anti-Ragging Cell & Helpline",
    description: "Zero-tolerance anti-ragging measures, squad contacts, national helpline, and online affidavit submission links.",
    url: "https://www.antiragging.in/",
    category: "campus_services",
    badge: "Safety 24x7",
    icon: "🛡️",
    tags: ["anti ragging", "ragging", "helpline", "discipline", "safety", "affidavit"],
  },
  {
    id: "grievance-redressal",
    title: "Online Student Grievance Portal",
    description: "Institutional grievance portal to register academic, hostel, administrative, or facility concerns with confidentiality.",
    url: "https://www.juit.ac.in/student-activities",
    category: "campus_services",
    badge: "Redressal",
    icon: "⚖️",
    tags: ["grievance", "complaint", "feedback", "support", "redressal"],
  },
  {
    id: "campus-transport",
    title: "Campus Transport & Bus Schedule",
    description: "Daily scheduled university buses connecting JUIT campus with Waknaghat, Solan town, and Shimla.",
    url: "https://www.juit.ac.in/contact/location",
    category: "campus_services",
    badge: "Bus Service",
    icon: "🚌",
    tags: ["transport", "bus", "bus schedule", "waknaghat", "solan", "shimla"],
  },
  {
    id: "medical-facilities",
    title: "Campus Health Centre & Dispensary",
    description: "On-campus 24x7 medical emergency care, resident doctors, nursing staff, ambulance service, and essential pharmacy.",
    url: "https://www.juit.ac.in/",
    category: "campus_services",
    badge: "Medical / Emergency",
    icon: "🏥",
    tags: ["medical", "doctor", "dispensary", "ambulance", "hospital", "health"],
  },
  {
    id: "campus-directions",
    title: "How to Reach JUIT & Location",
    description: "Official road maps, nearest railway stations (Waknaghat Toy Train, Kalka), airport connectivity and local taxi fares.",
    url: "https://www.juit.ac.in/contact/location",
    category: "campus_services",
    badge: "Travel Guide",
    icon: "📍",
    tags: ["reach", "location", "directions", "train", "taxi", "waknaghat", "nh-5"],
  },

  // ─── 🎭 STUDENT BODIES & SOCIETIES ─────────────────────────────────────────
  {
    id: "jyc-main",
    title: "Jaypee Youth Club (JYC)",
    description: "Apex student body overseeing cultural, technical, literary, environmental, and sports committees on campus.",
    url: "https://jyc.co.in",
    category: "student_bodies",
    badge: "Student Council",
    icon: "🎭",
    tags: ["jyc", "youth club", "fest", "committees", "student council"],
  },
  {
    id: "acm-chapter",
    title: "ACM Student Chapter JUIT",
    description: "Computing society organizing national coding hackathons, Murious tech fest, competitive programming workshops.",
    url: "https://juit.acm.org/",
    category: "student_bodies",
    badge: "Computing Society",
    icon: "💻",
    tags: ["acm", "coding", "murious", "hackathons", "computer science"],
  },
  {
    id: "ieee-branch",
    title: "IEEE Student Branch JUIT",
    description: "International engineering technical chapter hosting research symposiums, technical seminars, and robotic challenges.",
    url: "https://ieeejuitsb.in",
    category: "student_bodies",
    badge: "Tech Society",
    icon: "⚡",
    tags: ["ieee", "robotics", "electronics", "research", "seminars"],
  },
  {
    id: "nss-juit",
    title: "National Service Scheme (NSS)",
    description: "Community welfare unit organizing blood donation drives, health awareness in nearby villages, and tree plantations.",
    url: "https://www.juit.ac.in/nss/",
    category: "student_bodies",
    badge: "Community Welfare",
    icon: "🤝",
    tags: ["nss", "social service", "blood donation", "community", "volunteering"],
  },
];

export const JUIT_OFFICIAL_CONTACTS: JuitContactItem[] = [
  // ─── 🚨 24x7 CAMPUS & PUBLIC EMERGENCY HELPLINES ─────────────────────────
  {
    id: "security-emergency",
    role: "Campus Security & Central Control Room (24x7)",
    department: "Security & Safety",
    phone: "+91-1792-239222",
    email: "security@juit.ac.in",
    location: "Main Entrance Security Post & Central Control Desk",
    timing: "24 Hours / 7 Days (Direct On-Duty Security Officer)",
    isEmergency: true,
    category: "emergency",
    priority: 1,
  },
  {
    id: "medical-emergency",
    role: "Campus Medical Centre & Ambulance (24x7)",
    department: "Health Centre",
    phone: "+91-1792-239225",
    email: "medical@juit.ac.in",
    location: "Dispensary Block, Lower Terrace (Behind Hostels)",
    timing: "24 Hours / 7 Days (Doctor, Nurse & Ambulance On-Site)",
    isEmergency: true,
    category: "emergency",
    priority: 2,
  },
  {
    id: "national-emergency-112",
    role: "National Unified Emergency Helpline (Police / Medical / Fire)",
    department: "Govt of India / HP ERSS",
    phone: "112",
    location: "Pan-India / Himachal Pradesh (Instant Emergency Dispatch)",
    timing: "24 Hours / 7 Days (Toll-Free Pan-India)",
    isEmergency: true,
    category: "emergency",
    priority: 3,
  },
  {
    id: "kandaghat-police",
    role: "Kandaghat Police Station (Waknaghat Jurisdiction)",
    department: "HP Police",
    phone: "01792-256124",
    location: "NH-05, Kandaghat (Approx. 7 km from Waknaghat Chowk)",
    timing: "24 Hours / 7 Days (Local Police Jurisdiction Thana)",
    isEmergency: true,
    category: "police_safety",
    priority: 4,
  },
  {
    id: "solan-police-control",
    role: "Solan District Police Control Room & PCR",
    department: "HP Police Solan HQ",
    phone: "01792-220567",
    location: "Superintendent of Police Office & Control Room, Solan",
    timing: "24 Hours / 7 Days (Emergency PCR Dispatch)",
    isEmergency: true,
    category: "police_safety",
    priority: 5,
  },
  {
    id: "anti-ragging-national",
    role: "National Anti-Ragging Helpline (UGC 24x7)",
    department: "Ministry of Education / UGC",
    phone: "1800-180-5522",
    email: "helpline@antiragging.in",
    location: "National 24x7 Anti-Ragging Call Centre",
    timing: "24 Hours / 7 Days (Toll-Free, Zero-Tolerance, Confidential)",
    isEmergency: true,
    category: "emergency",
    priority: 6,
  },
  {
    id: "juit-anti-ragging",
    role: "JUIT Anti-Ragging Committee & Flying Squad",
    department: "Student Welfare",
    phone: "+91-1792-239204",
    email: "antiragging@juit.ac.in",
    location: "Office of Dean of Students Welfare, Academic Block I",
    timing: "24x7 On-Call Campus Vigilance Squad",
    isEmergency: true,
    category: "emergency",
    priority: 7,
  },
  {
    id: "women-helpline",
    role: "Women Safety & Distress Helpline (HP & National)",
    department: "Women & Child Safety",
    phone: "1091",
    email: "icc@juit.ac.in",
    location: "HP Women Safety Cell / JUIT Internal Complaints Committee",
    timing: "24 Hours / 7 Days (Toll-Free, Confidential Helpline: 1091 / 181)",
    isEmergency: true,
    category: "police_safety",
    priority: 8,
  },
  {
    id: "hospital-solan",
    role: "Regional Hospital Solan (Civil Hospital & Trauma Centre)",
    department: "Health & Family Welfare HP",
    phone: "01792-224147",
    location: "Circular Road, Solan (18 km from JUIT Campus)",
    timing: "24 Hours Emergency Casualty, ICU & Blood Bank",
    isEmergency: true,
    category: "health_hostel",
    priority: 9,
  },
  {
    id: "chc-kandaghat",
    role: "Community Health Centre Kandaghat (Nearest CHC)",
    department: "HP Health Services",
    phone: "01792-256123",
    location: "Kandaghat Market, NH-05 (Approx. 7 km from Waknaghat)",
    timing: "24 Hours Emergency Casualty & First-Referral Medical Unit",
    isEmergency: true,
    category: "health_hostel",
    priority: 10,
  },
  {
    id: "igmc-shimla",
    role: "IGMC Hospital Shimla (Tertiary Care & Level-1 Trauma)",
    department: "Indira Gandhi Medical College",
    phone: "0177-2804251",
    location: "Circular Road / Lakkar Bazaar, Shimla (Approx. 24 km)",
    timing: "24 Hours Apex Tertiary Emergency & Advanced Trauma Care",
    isEmergency: true,
    category: "health_hostel",
    priority: 11,
  },
  {
    id: "tele-manas",
    role: "Tele-MANAS National Mental Health & Counseling Helpline",
    department: "Ministry of Health & Family Welfare",
    phone: "14416",
    email: "counselor@juit.ac.in",
    location: "National Tele-Mental Health Centre (Toll-Free 24x7)",
    timing: "24 Hours / 7 Days (Free, Confidential Psychological Support & Guidance)",
    isEmergency: true,
    category: "emergency",
    priority: 12,
  },
  {
    id: "disaster-helpline",
    role: "State & District Disaster Management Helpline (SDMA)",
    department: "Disaster Management Cell HP",
    phone: "1077",
    location: "District Emergency Operation Centre Solan / State Control Room (1070)",
    timing: "24 Hours / 7 Days (Landslide, Flash Flood, Weather & Road Alerts)",
    isEmergency: true,
    category: "emergency",
    priority: 13,
  },
  {
    id: "fire-emergency",
    role: "Fire & Rescue Emergency Services (Solan Station)",
    department: "HP Fire Services",
    phone: "101",
    location: "Solan Fire Station (Landline: 01792-223888)",
    timing: "24 Hours / 7 Days Emergency Fire & Disaster Rescue",
    isEmergency: true,
    category: "emergency",
    priority: 14,
  },
  {
    id: "hostel-warden-emergency",
    role: "Chief Warden Office & Emergency Hostel Warden Desk",
    department: "Hostels & Residence",
    phone: "+91-1792-239212",
    email: "hostel@juit.ac.in",
    location: "Chief Warden Office, Near Annapurna Dining Hall",
    timing: "24x7 Emergency Warden on Duty (Boys & Girls Hostels)",
    isEmergency: true,
    category: "health_hostel",
    priority: 15,
  },

  // ─── 🏫 UNIVERSITY ADMINISTRATIVE & ACADEMIC OFFICES ───────────────────
  {
    id: "reception",
    role: "General University Reception (EPABX)",
    department: "Administration",
    phone: "+91-1792-239200",
    email: "info@juit.ac.in",
    location: "Main Gate & Admin Block Reception",
    timing: "09:00 AM – 05:00 PM (Mon – Sat)",
    category: "administration",
    priority: 20,
  },
  {
    id: "academic-office",
    role: "Academic Affairs & Registrar Office",
    department: "Academics",
    phone: "+91-1792-239203",
    email: "academic@juit.ac.in",
    location: "Academic Block I, Administrative Wing",
    timing: "09:00 AM – 05:00 PM (Mon – Sat)",
    category: "administration",
    priority: 21,
  },
  {
    id: "dsw",
    role: "Dean of Students Welfare (DSW)",
    department: "Student Welfare",
    phone: "+91-1792-239204",
    email: "dean.sw@juit.ac.in",
    location: "Academic Block I, Office of DSW",
    timing: "09:30 AM – 05:00 PM",
    category: "administration",
    priority: 22,
  },
  {
    id: "library-lrc",
    role: "Learning Resource Centre (Central Library)",
    department: "LRC Library",
    phone: "+91-1792-239288",
    email: "library@juit.ac.in",
    location: "LRC 3-Storey Central Library Building",
    timing: "08:45 AM – 12:00 Midnight",
    category: "administration",
    priority: 23,
  },
  {
    id: "placement",
    role: "Training & Placement Cell (T&P)",
    department: "Career Services",
    phone: "+91-1792-239285",
    email: "placement@juit.ac.in",
    location: "Academic Block II, T&P Wing",
    timing: "09:00 AM – 05:00 PM",
    category: "administration",
    priority: 24,
  },
  {
    id: "it-helpdesk",
    role: "Computer Centre & Network Cell",
    department: "IT Services",
    phone: "+91-1792-239230",
    email: "cc@juit.ac.in",
    location: "Academic Block II, Ground Floor",
    timing: "09:00 AM – 06:00 PM",
    category: "administration",
    priority: 25,
  },
  {
    id: "finance-accounts",
    role: "Finance & Accounts Office (Student Fees & Dues)",
    department: "Finance",
    phone: "+91-1792-239228",
    email: "accounts@juit.ac.in",
    location: "Admin Block, 1st Floor",
    timing: "09:30 AM – 05:00 PM (Mon – Sat)",
    category: "administration",
    priority: 26,
  },
  {
    id: "vc-secretariat",
    role: "Vice Chancellor / Director Secretariat",
    department: "Executive Leadership",
    phone: "+91-1792-239201",
    email: "director@juit.ac.in",
    location: "Administrative Block, Executive Suite",
    timing: "09:30 AM – 05:00 PM",
    category: "administration",
    priority: 27,
  },
];
