export interface SyllabusSubject {
  code: string;
  name: string;
  category: "BSC" | "ESC" | "HSC" | "PCC" | "PEC" | "OEC" | "PRC" | "OMC" | "Audit";
  type: "theory" | "lab" | "elective" | "project" | "other";
  credits: string;
  lectureHours?: string; // e.g. "3-1-0" or "0-0-2"
  description: string;
  electiveOptions?: string[];
}

export interface SyllabusSemester {
  semNumber: number;
  label: string;
  year: 1 | 2 | 3 | 4;
  term: "Odd (Fall)" | "Even (Spring)";
  totalCredits: number;
  description: string;
  subjects: SyllabusSubject[];
}

export interface SyllabusYear {
  year: 1 | 2 | 3 | 4;
  title: string;
  stage: string;
  description: string;
  semesters: [number, number]; // [oddSem, evenSem]
}

export const SYLLABUS_YEARS: SyllabusYear[] = [
  {
    year: 1,
    title: "1st Year (Freshman)",
    stage: "Foundation & Core Sciences",
    description: "Mathematics, Physics, Basic Electronics, and C/C++ Programming fundamentals.",
    semesters: [1, 2],
  },
  {
    year: 2,
    title: "2nd Year (Sophomore)",
    stage: "Core Computer Science",
    description: "Data Structures, DBMS, Automata Theory, Algorithms, AI/ML, and Computer Architecture.",
    semesters: [3, 4],
  },
  {
    year: 3,
    title: "3rd Year (Junior)",
    stage: "Systems, Software & Advanced CS",
    description: "Operating Systems, Computer Networks, Web Technologies, Advanced DSA, Cloud, and Electives.",
    semesters: [5, 6],
  },
  {
    year: 4,
    title: "4th Year (Senior)",
    stage: "Specialization & Capstone Projects",
    description: "Major Projects Part 1 & 2, Industrial Internships, Advanced Domain Electives, and Open Electives.",
    semesters: [7, 8],
  },
];

export const JUIT_SYLLABUS_SEMESTERS: SyllabusSemester[] = [
  // ──────────────────────────────────────────────────────────────────────────
  // YEAR 1: SEMESTER 1
  // ──────────────────────────────────────────────────────────────────────────
  {
    semNumber: 1,
    label: "Semester 1",
    year: 1,
    term: "Odd (Fall)",
    totalCredits: 24.5,
    description: "Introduction to collegiate mathematics, engineering physics, procedural programming in C, and electronics.",
    subjects: [
      {
        code: "25B11MA111",
        name: "Mathematics-I",
        category: "BSC",
        type: "theory",
        credits: "4.0",
        lectureHours: "3-1-0",
        description: "Differential and integral calculus, multivariable functions, linear algebra, matrices, eigenvalues, and vector calculus.",
      },
      {
        code: "25B11PH111",
        name: "Physics-I",
        category: "BSC",
        type: "theory",
        credits: "4.0",
        lectureHours: "3-1-0",
        description: "Wave optics, interference, diffraction, lasers, fiber optics, electromagnetic theory, and introductory quantum mechanics.",
      },
      {
        code: "25B11CI112",
        name: "Software Development Fundamentals-I",
        category: "ESC",
        type: "theory",
        credits: "4.0",
        lectureHours: "3-1-0",
        description: "Problem solving, flowcharts, C language syntax, control structures, functions, arrays, pointers, dynamic memory, and file I/O.",
      },
      {
        code: "25B11EC111",
        name: "Basic Electronics",
        category: "ESC",
        type: "theory",
        credits: "4.0",
        lectureHours: "3-1-0",
        description: "Semiconductor diodes, rectifiers, BJTs, JFETs/MOSFETs, Operational Amplifiers (Op-Amps), and digital logic gates.",
      },
      {
        code: "25B11HS111",
        name: "English",
        category: "HSC",
        type: "theory",
        credits: "2.0",
        lectureHours: "2-0-0",
        description: "Technical communication, grammar, technical writing, professional email etiquette, presentation skills, and reading comprehension.",
      },
      {
        code: "25B17PH171",
        name: "Physics Lab-I",
        category: "BSC",
        type: "lab",
        credits: "1.0",
        lectureHours: "0-0-2",
        description: "Experiments on Newton's rings, diffraction grating, Hall effect, spectrometer, laser wavelength, and semiconductor band gap.",
      },
      {
        code: "25B17CI172",
        name: "Software Development Fundamentals Lab-I",
        category: "ESC",
        type: "lab",
        credits: "1.0",
        lectureHours: "0-0-2",
        description: "Hands-on implementation of procedural algorithms in C: loops, matrices, recursion, pointers, linked lists, and file manipulation.",
      },
      {
        code: "25B17EC171",
        name: "Basic Electronics Lab",
        category: "ESC",
        type: "lab",
        credits: "1.0",
        lectureHours: "0-0-2",
        description: "Lab verification of P-N junction characteristics, Zener voltage regulators, transistor amplifiers, Op-Amp circuits, and logic gates.",
      },
      {
        code: "25B17GE171",
        name: "Workshop",
        category: "ESC",
        type: "lab",
        credits: "1.5",
        lectureHours: "0-0-3",
        description: "Engineering practice: Fitting, carpentry, electrical wiring, welding, PCB fabrication, and computer hardware assembly.",
      },
    ],
  },

  // ──────────────────────────────────────────────────────────────────────────
  // YEAR 1: SEMESTER 2
  // ──────────────────────────────────────────────────────────────────────────
  {
    semNumber: 2,
    label: "Semester 2",
    year: 1,
    term: "Even (Spring)",
    totalCredits: 23.5,
    description: "Advanced calculus, solid state physics, Object-Oriented C++ programming, human values, and engineering drawing.",
    subjects: [
      {
        code: "25B11MA112",
        name: "Mathematics-II",
        category: "BSC",
        type: "theory",
        credits: "4.0",
        lectureHours: "3-1-0",
        description: "Ordinary & partial differential equations (ODEs/PDEs), complex analysis, Cauchy-Riemann equations, and Fourier series.",
      },
      {
        code: "25B11PH112",
        name: "Physics-II",
        category: "BSC",
        type: "theory",
        credits: "4.0",
        lectureHours: "3-1-0",
        description: "Solid state physics, crystal structures, band theory of solids, semiconductor transport, dielectrics, and superconductivity.",
      },
      {
        code: "25B11CI113",
        name: "Software Development Fundamentals-II",
        category: "ESC",
        type: "theory",
        credits: "4.0",
        lectureHours: "3-1-0",
        description: "Object-oriented programming in C++: classes, constructors, inheritance, runtime polymorphism, templates, STL, and exceptions.",
      },
      {
        code: "25B11HS112",
        name: "Universal Human Values (UHV)",
        category: "HSC",
        type: "theory",
        credits: "3.0",
        lectureHours: "3-0-0",
        description: "Human values, self-exploration, harmony in self, family, society, and nature, professional ethics, and holistic development.",
      },
      {
        code: "25B17PH172",
        name: "Physics Lab-II",
        category: "BSC",
        type: "lab",
        credits: "1.0",
        lectureHours: "0-0-2",
        description: "Measurements with four-probe resistivity, B-H curve tracer, solar cell efficiency, ultrasonic interferometer, and Planck constant.",
      },
      {
        code: "25B17CI173",
        name: "Software Development Fundamentals Lab-II",
        category: "ESC",
        type: "lab",
        credits: "1.0",
        lectureHours: "0-0-2",
        description: "C++ OOP lab exercises: operator overloading, inheritance hierarchies, abstract base classes, STL containers, and custom templates.",
      },
      {
        code: "25B17HS171",
        name: "Life Skills & Professional Communication Lab",
        category: "HSC",
        type: "lab",
        credits: "1.0",
        lectureHours: "0-0-2",
        description: "Interactive communication sessions: Group Discussions (GDs), public speaking, mock HR interviews, and professional presentation practice.",
      },
      {
        code: "25B17GE172",
        name: "Engineering Drawing & Design",
        category: "ESC",
        type: "lab",
        credits: "1.5",
        lectureHours: "0-0-3",
        description: "Orthographic projections, isometric projections, section of solids, dimensioning standards, and 2D drafting in AutoCAD.",
      },
    ],
  },

  // ──────────────────────────────────────────────────────────────────────────
  // YEAR 2: SEMESTER 3
  // ──────────────────────────────────────────────────────────────────────────
  {
    semNumber: 3,
    label: "Semester 3",
    year: 2,
    term: "Odd (Fall)",
    totalCredits: 24.0,
    description: "The core foundation of Computer Science: Data structures, Relational databases, Automata theory, Java, and Linux environments.",
    subjects: [
      {
        code: "25B11CI318",
        name: "Data Structures",
        category: "PCC",
        type: "theory",
        credits: "4.0",
        lectureHours: "3-1-0",
        description: "Arrays, stacks, queues, linked lists, binary trees, BST, AVL trees, heaps, B-trees, graph traversals, and hashing techniques.",
      },
      {
        code: "25B11CI313",
        name: "Database Management Systems",
        category: "PCC",
        type: "theory",
        credits: "3.0",
        lectureHours: "3-0-0",
        description: "Relational database models, ER diagrams, SQL, normalization (1NF to BCNF), transaction ACID properties, indexing, and NoSQL basics.",
      },
      {
        code: "25B11CI315",
        name: "Theory of Computation",
        category: "PCC",
        type: "theory",
        credits: "3.0",
        lectureHours: "3-0-0",
        description: "Finite automata (DFA/NFA), regular expressions, context-free grammars, pushdown automata (PDA), Turing machines, and decidability.",
      },
      {
        code: "25B11MA314",
        name: "Mathematical Foundations for AI & Data Science",
        category: "BSC",
        type: "theory",
        credits: "3.0",
        lectureHours: "3-0-0",
        description: "Probability distributions, Bayes rule, random variables, hypothesis testing, linear algebra for ML, PCA, SVD, and gradient descent.",
      },
      {
        code: "25B17CI376",
        name: "Object Oriented Programming Using Java",
        category: "PCC",
        type: "theory",
        credits: "2.0",
        lectureHours: "1-0-2",
        description: "Java fundamentals, OOP principles, interfaces, packages, exception handling, multithreading, Collections framework, and JDBC.",
      },
      {
        code: "25B11HS311",
        name: "Economics",
        category: "HSC",
        type: "theory",
        credits: "3.0",
        lectureHours: "3-0-0",
        description: "Engineering economics: demand & supply, cost functions, market competition, national income, inflation, and investment appraisal.",
      },
      {
        code: "25B17CI380",
        name: "Data Structures Lab",
        category: "PCC",
        type: "lab",
        credits: "1.0",
        lectureHours: "0-0-2",
        description: "Implementation of stacks, queues, linked lists, binary trees, BST operations, AVL rotations, graph BFS/DFS, and hash tables.",
      },
      {
        code: "25B17CI373",
        name: "DBMS Lab",
        category: "PCC",
        type: "lab",
        credits: "1.0",
        lectureHours: "0-0-2",
        description: "Interactive SQL queries: DDL, DML, complex joins, nested subqueries, views, triggers, stored procedures, and full application linkage.",
      },
      {
        code: "25B17CI375",
        name: "UNIX Programming Lab",
        category: "PCC",
        type: "lab",
        credits: "2.0",
        lectureHours: "0-0-4",
        description: "Linux shell command line, Bash scripting, regex with sed & awk, POSIX system calls (fork, exec, pipe), and process control.",
      },
      {
        code: "25B17CI379",
        name: "Competitive Programming-I",
        category: "PCC",
        type: "lab",
        credits: "1.0",
        lectureHours: "0-0-2",
        description: "Fast I/O, two pointers, sliding window, prefix sums, binary search on answer, bit manipulation, and online judge problem solving.",
      },
      {
        code: "25B19CI391",
        name: "Summer Training-I (4 weeks)",
        category: "PRC",
        type: "project",
        credits: "2.0",
        lectureHours: "0-0-0",
        description: "Evaluation of 4-week summer internship or mini-project completed after 1st year: report submission, presentation, and viva-voce.",
      },
    ],
  },

  // ──────────────────────────────────────────────────────────────────────────
  // YEAR 2: SEMESTER 4
  // ──────────────────────────────────────────────────────────────────────────
  {
    semNumber: 4,
    label: "Semester 4",
    year: 2,
    term: "Even (Spring)",
    totalCredits: 23.0,
    description: "Algorithm design paradigms, Machine learning foundations, Computer architecture, and Software engineering lifecycle.",
    subjects: [
      {
        code: "25B11CI411",
        name: "Design and Analysis of Algorithms",
        category: "PCC",
        type: "theory",
        credits: "3.0",
        lectureHours: "3-0-0",
        description: "Divide & conquer, greedy methods, dynamic programming, backtracking, branch & bound, graph algorithms, and NP-completeness.",
      },
      {
        code: "25B11CI412",
        name: "Artificial Intelligence and Machine Learning",
        category: "PCC",
        type: "theory",
        credits: "3.0",
        lectureHours: "3-0-0",
        description: "Search strategies (A*, minimax), supervised learning (regression, decision trees, SVM), unsupervised clustering, neural nets, and evaluation metrics.",
      },
      {
        code: "25B11CI413",
        name: "Digital Systems and Computer Organisation",
        category: "PCC",
        type: "theory",
        credits: "4.0",
        lectureHours: "3-1-0",
        description: "Digital combinational/sequential logic, instruction set architecture (ISA), CPU datapath & pipelining, cache memory, and I/O interfacing.",
      },
      {
        code: "25B11CI414",
        name: "Software Engineering",
        category: "PCC",
        type: "theory",
        credits: "3.0",
        lectureHours: "3-0-0",
        description: "SDLC models, Agile/Scrum framework, SRS documentation, UML design diagrams, design patterns, software testing (unit, integration), and CI/CD basics.",
      },
      {
        code: "25B14CI41X",
        name: "Discipline Elective - 1 (+ Lab)",
        category: "PEC",
        type: "elective",
        credits: "3.0",
        lectureHours: "2-0-2",
        description: "Choose 1 specialized technical elective bucket offering foundational knowledge in modern development domains.",
        electiveOptions: [
          "Front-End Development Basics (HTML5, Modern CSS, JavaScript ES6+, DOM)",
          "Introduction to UI-UX Design (Wireframing, Figma, User Research, Prototyping)",
          "Information and Cyber Security Foundations (Threat models, Cryptography basics, Ethical Hacking)",
        ],
      },
      {
        code: "25B14HS41X",
        name: "HSS Elective - 1",
        category: "HSC",
        type: "elective",
        credits: "3.0",
        lectureHours: "3-0-0",
        description: "Humanities elective providing sociological, cognitive, or ethical grounding for engineers.",
        electiveOptions: [
          "Industrial Sociology (Work organization, Labor laws, Industry dynamics)",
          "Cognitive Psychology (Human behavior, Decision making, Perception)",
          "Professional Ethics and Values (Corporate responsibility, Engineering codes)",
        ],
      },
      {
        code: "25B17CI471",
        name: "Design and Analysis of Algorithms Lab",
        category: "PCC",
        type: "lab",
        credits: "1.0",
        lectureHours: "0-0-2",
        description: "Lab benchmarking: Merge sort, Quick sort, Prim/Kruskal MST, Dijkstra, 0/1 Knapsack DP, Matrix chain multiplication, and N-Queens.",
      },
      {
        code: "25B17CI472",
        name: "AI & ML Lab",
        category: "PCC",
        type: "lab",
        credits: "1.0",
        lectureHours: "0-0-2",
        description: "Hands-on Python ML: NumPy, Pandas, Scikit-learn models (Regression, KNN, Decision Trees), K-Means, and building a PyTorch neural net.",
      },
      {
        code: "25B17CI473",
        name: "Digital Systems & Computer Organisation Lab",
        category: "PCC",
        type: "lab",
        credits: "1.0",
        lectureHours: "0-0-2",
        description: "Circuit simulations in Logisim / Proteus: Adders, multiplexers, counters, registers, ALU design, and cache hit/miss simulator.",
      },
      {
        code: "25B17CI474",
        name: "Competitive Programming-II",
        category: "PEC",
        type: "lab",
        credits: "1.0",
        lectureHours: "0-0-2",
        description: "Intermediate competitive programming: Disjoint Set Union (DSU), Shortest path variants, Modular arithmetic, and DP on grids.",
      },
      {
        code: "25B11GE411",
        name: "Environmental Studies",
        category: "OMC",
        type: "other",
        credits: "Qualifying",
        lectureHours: "2-0-0",
        description: "Ecosystems, natural resource conservation, biodiversity hotspots, environmental pollution control, climate change, and sustainability laws.",
      },
    ],
  },

  // ──────────────────────────────────────────────────────────────────────────
  // YEAR 3: SEMESTER 5
  // ──────────────────────────────────────────────────────────────────────────
  {
    semNumber: 5,
    label: "Semester 5",
    year: 3,
    term: "Odd (Fall)",
    totalCredits: 24.0,
    description: "Deep dive into Operating Systems, Computer Networks, Full Stack Web engineering, and domain electives.",
    subjects: [
      {
        code: "25B11CI511",
        name: "Operating Systems",
        category: "PCC",
        type: "theory",
        credits: "4.0",
        lectureHours: "3-1-0",
        description: "Kernel architecture, process scheduling, synchronization, semaphores, deadlocks, virtual memory paging, and file system disk scheduling.",
      },
      {
        code: "25B11CI512",
        name: "Computer Networks",
        category: "PCC",
        type: "theory",
        credits: "4.0",
        lectureHours: "3-1-0",
        description: "OSI and TCP/IP stack, physical framing, error detection, IPv4/IPv6 addressing, routing (OSPF, BGP), TCP flow/congestion control, and DNS/HTTP.",
      },
      {
        code: "25B14CI51X",
        name: "Discipline Elective - 2 (+ Lab)",
        category: "PEC",
        type: "elective",
        credits: "3.0",
        lectureHours: "2-0-2",
        description: "Specialized domain elective covering cloud infrastructure, mobile development, or applied network security.",
        electiveOptions: [
          "Cloud Computing Technologies (Virtualization, Docker, Kubernetes, AWS/GCP architecture)",
          "Mobile Application Development (Flutter, Dart, Android Studio, Cross-platform apps)",
          "Cryptography & Network Security (AES, RSA, ECC, Digital Signatures, PKI, Firewalls)",
        ],
      },
      {
        code: "25B14CI52X",
        name: "Discipline Elective - 3 (+ Lab)",
        category: "PEC",
        type: "elective",
        credits: "3.0",
        lectureHours: "2-0-2",
        description: "Advanced computational elective focusing on deep neural systems, big data warehousing, or language compilers.",
        electiveOptions: [
          "Deep Learning & Neural Networks (CNNs, RNNs, LSTMs, Transformers, PyTorch)",
          "Data Mining & Data Warehousing (ETL pipelines, Association rule mining, OLAP)",
          "Compiler Design (Lexical analysis, Lex/Yacc, Parsing, Code generation, Optimization)",
        ],
      },
      {
        code: "25B14MA51X",
        name: "Science Elective",
        category: "BSC",
        type: "elective",
        credits: "3.0",
        lectureHours: "3-0-0",
        description: "Applied mathematics elective supporting scientific computing and data modeling.",
        electiveOptions: [
          "Numerical Techniques & Scientific Computing (Root finding, Numerical ODE, Splines)",
          "Operations Research (Linear programming, Simplex, Transportation, Queuing theory)",
          "Graph Theory & Combinatorics (Planar graphs, Coloring, Matching, Network flows)",
        ],
      },
      {
        code: "25B17CI571",
        name: "Full Stack Development Lab",
        category: "PEC",
        type: "lab",
        credits: "1.0",
        lectureHours: "0-0-2",
        description: "Building production-grade web apps: React/Next.js frontend, Node.js/Express REST APIs, MongoDB/PostgreSQL database, and cloud deployment.",
      },
      {
        code: "25B17CI572",
        name: "Operating Systems Lab",
        category: "PCC",
        type: "lab",
        credits: "1.0",
        lectureHours: "0-0-2",
        description: "Linux system programming: fork/exec process creation, POSIX pthreads, semaphores, mutex locks, CPU scheduling simulation, and Banker algorithm.",
      },
      {
        code: "25B17CI573",
        name: "Computer Networks Lab",
        category: "PCC",
        type: "lab",
        credits: "1.0",
        lectureHours: "0-0-2",
        description: "Socket programming in Python/C, packet sniffing with Wireshark, router configuration and subnetting in Cisco Packet Tracer.",
      },
      {
        code: "25B17CI574",
        name: "Competitive Programming-III",
        category: "PCC",
        type: "lab",
        credits: "1.0",
        lectureHours: "0-0-2",
        description: "Advanced CP algorithms: Segment trees, Fenwick trees, Tree DP, String hashing, Trie structures, and Codeforces Div 2 contest preparation.",
      },
      {
        code: "25B11HS511",
        name: "Logical and Quantitative Techniques-I",
        category: "HSC",
        type: "theory",
        credits: "2.0",
        lectureHours: "2-0-0",
        description: "Placement preparation: Quantitative aptitude (Speed/Time, Permutations, Probability, Work), logical reasoning, and analytical problem solving.",
      },
      {
        code: "25B19CI591",
        name: "Summer Training-II (6 weeks)",
        category: "PRC",
        type: "project",
        credits: "2.0",
        lectureHours: "0-0-0",
        description: "6-week summer internship or institutional research project completed after 4th semester: evaluation, report, and seminar defense.",
      },
      {
        code: "25B11HS512",
        name: "Indian Constitution & Traditional Knowledge",
        category: "HSC",
        type: "other",
        credits: "Qualifying",
        lectureHours: "2-0-0",
        description: "Constitutional framework, fundamental rights, directive principles, Indian judicial system, and traditional knowledge heritage.",
      },
    ],
  },

  // ──────────────────────────────────────────────────────────────────────────
  // YEAR 3: SEMESTER 6
  // ──────────────────────────────────────────────────────────────────────────
  {
    semNumber: 6,
    label: "Semester 6",
    year: 3,
    term: "Even (Spring)",
    totalCredits: 23.0,
    description: "Advanced web engineering, advanced algorithm design, distributed cloud systems, capstone minor project, and placement readiness.",
    subjects: [
      {
        code: "25B11CI611",
        name: "Web Technology",
        category: "PCC",
        type: "theory",
        credits: "3.0",
        lectureHours: "3-0-0",
        description: "Modern web architecture, TypeScript, state management, REST & GraphQL APIs, WebSockets, OAuth2 security, and serverless compute.",
      },
      {
        code: "25B11CI612",
        name: "Advanced Data Structures and Algorithms",
        category: "PCC",
        type: "theory",
        credits: "3.0",
        lectureHours: "3-0-0",
        description: "Red-black trees, Splay trees, B+ trees, KMP string search, max network flows (Ford-Fulkerson), computational geometry, and randomized algorithms.",
      },
      {
        code: "25B11CI613",
        name: "Distributed & Cloud Computing OR Info. Security & Cryptography",
        category: "PCC",
        type: "theory",
        credits: "3.0",
        lectureHours: "3-0-0",
        description: "Distributed consensus (Raft/Paxos), microservices, Kubernetes, cloud storage models, symmetric/asymmetric cryptography, and web threat mitigation.",
      },
      {
        code: "25B14CI61X",
        name: "Discipline Elective - 4",
        category: "PEC",
        type: "elective",
        credits: "3.0",
        lectureHours: "3-0-0",
        description: "Specialized artificial intelligence, big data analytics, or computer vision track.",
        electiveOptions: [
          "Natural Language Processing (Text preprocessing, Word2Vec, Transformers, LLM fine-tuning)",
          "Big Data Analytics (Hadoop HDFS, MapReduce, Apache Spark, NoSQL query engines)",
          "Computer Vision & Image Processing (Feature extraction, CNNs, Object detection YOLO, OpenCV)",
        ],
      },
      {
        code: "25B14CI62X",
        name: "Discipline Elective - 5",
        category: "PEC",
        type: "elective",
        credits: "3.0",
        lectureHours: "3-0-0",
        description: "Emerging engineering practices covering DevOps pipelines, IoT devices, or decentralized systems.",
        electiveOptions: [
          "DevOps Engineering & SRE (Docker, Kubernetes, Jenkins, GitHub Actions, Terraform, Monitoring)",
          "Internet of Things (IoT) & Embedded Systems (Raspberry Pi, ESP32, MQTT protocols, Sensor networks)",
          "Blockchain Technologies & Smart Contracts (Ethereum, Solidity, Decentralized consensus, Web3)",
        ],
      },
      {
        code: "25B14OE61X",
        name: "Open Elective - 1",
        category: "OEC",
        type: "elective",
        credits: "3.0",
        lectureHours: "3-0-0",
        description: "Interdisciplinary elective from Biotechnology, Civil Engineering, or Management departments.",
        electiveOptions: [
          "Bio-Informatics & Computational Biology (Sequence alignment, Genomic databases, BLAST)",
          "Disaster Mitigation & Management (Geological hazards, Risk analysis, Safety protocols)",
          "Total Quality Management (Six Sigma, Quality control standards, Industrial metrics)",
        ],
      },
      {
        code: "25B17CI671",
        name: "Web Technology Lab",
        category: "PCC",
        type: "lab",
        credits: "1.0",
        lectureHours: "0-0-2",
        description: "Development of reactive web applications: Node.js server, JWT authentication, Next.js routing, real-time WebSocket chat, and Docker containers.",
      },
      {
        code: "25B17CI672",
        name: "Advanced DSA Lab",
        category: "PCC",
        type: "lab",
        credits: "1.0",
        lectureHours: "0-0-2",
        description: "Implementation of Red-Black trees, KMP string matching, Ford-Fulkerson network flow, Skip lists, and Convex Hull algorithms.",
      },
      {
        code: "25B19CI691",
        name: "Minor Project",
        category: "PRC",
        type: "project",
        credits: "2.0",
        lectureHours: "0-0-4",
        description: "Group capstone project: formulating a real-world problem, designing architectural modules, implementing a working prototype, and presenting before faculty.",
      },
      {
        code: "25B11HS611",
        name: "Soft Skills for Employability",
        category: "HSC",
        type: "lab",
        credits: "1.0",
        lectureHours: "1-0-0",
        description: "Corporate placement readiness: Mock technical interviews, HR screening rounds, resume tuning, leadership simulations, and case studies.",
      },
      {
        code: "25B11HS612",
        name: "Logical and Quantitative Techniques-II",
        category: "HSC",
        type: "theory",
        credits: "2.0",
        lectureHours: "2-0-0",
        description: "Advanced placement assessment training: Data interpretation (charts, tables), critical reasoning, syllogisms, and company-specific aptitude exams.",
      },
    ],
  },

  // ──────────────────────────────────────────────────────────────────────────
  // YEAR 4: SEMESTER 7
  // ──────────────────────────────────────────────────────────────────────────
  {
    semNumber: 7,
    label: "Semester 7",
    year: 4,
    term: "Odd (Fall)",
    totalCredits: 15.0,
    description: "Capstone major project formulation, corporate summer internship evaluation, advanced domain electives, and placement season.",
    subjects: [
      {
        code: "25B19CI791",
        name: "Major Project Part - 1",
        category: "PRC",
        type: "project",
        credits: "4.0",
        lectureHours: "0-0-8",
        description: "Final year capstone research/industry project: problem formulation, extensive literature review, SRS, high-level architecture design, and midterm demo.",
      },
      {
        code: "25B19CI792",
        name: "Summer Training - III (6 weeks)",
        category: "PRC",
        type: "project",
        credits: "4.0",
        lectureHours: "0-0-0",
        description: "Comprehensive 6 to 8-week corporate software engineering or research internship completed during summer: report, company feedback, and viva defense.",
      },
      {
        code: "25B14CI71X",
        name: "Discipline Elective - 6",
        category: "PEC",
        type: "elective",
        credits: "3.0",
        lectureHours: "3-0-0",
        description: "Advanced specialization elective exploring frontier computer science fields.",
        electiveOptions: [
          "Quantum Computing & Quantum Information (Qubits, Quantum gates, Shor and Grover algorithms, Qiskit)",
          "Reinforcement Learning (MDPs, Q-Learning, Policy Gradients, Deep Q Networks, Actor-Critic)",
          "High Performance Computing (MPI, OpenMP, GPU programming with CUDA, Parallel architectures)",
          "Digital Forensics & Incident Response (Memory forensics, Network packet analysis, Malware triage)",
        ],
      },
      {
        code: "25B14OE71X",
        name: "Open Elective - 2",
        category: "OEC",
        type: "elective",
        credits: "3.0",
        lectureHours: "3-0-0",
        description: "Interdisciplinary open elective covering innovation, intellectual property, or management.",
        electiveOptions: [
          "Entrepreneurship & Startup Management (Venture ideation, Business models, Funding, Product-market fit)",
          "Intellectual Property Rights & Patent Law (Patents, Trademarks, Copyrights, WIPO regulations)",
          "Financial Management for Engineers (Corporate finance, Valuation, Capital budgeting, Stock markets)",
          "Disaster Mitigation and Management (Risk assessment, Geo-spatial mapping, Emergency preparedness)",
        ],
      },
    ],
  },

  // ──────────────────────────────────────────────────────────────────────────
  // YEAR 4: SEMESTER 8
  // ──────────────────────────────────────────────────────────────────────────
  {
    semNumber: 8,
    label: "Semester 8",
    year: 4,
    term: "Even (Spring)",
    totalCredits: 14.0,
    description: "Final capstone project implementation & thesis defense OR full-semester 6-month corporate internship, plus elective options.",
    subjects: [
      {
        code: "25B19CI891",
        name: "Major Project Part - 2",
        category: "PRC",
        type: "project",
        credits: "8.0",
        lectureHours: "0-0-16",
        description: "Final implementation, testing, benchmarking, research paper submission, thesis dissertation drafting, and final viva-voce examination (OR 6-Month Full-Semester Industry Internship).",
      },
      {
        code: "25B14CI81X",
        name: "Discipline Elective - 7",
        category: "PEC",
        type: "elective",
        credits: "3.0",
        lectureHours: "3-0-0",
        description: "State-of-the-art domain elective focusing on next-generation computing systems.",
        electiveOptions: [
          "Autonomous Systems & Robotics (ROS, Kinematics, SLAM, Path planning, Sensor fusion)",
          "Edge AI & TinyML (Model quantization, Pruning, On-device inference, Embedded microcontrollers)",
          "Software Defined Networks (SDN architecture, OpenFlow, Network virtualization, P4)",
          "AI in Healthcare & Biomedical Informatics (Medical imaging, Diagnostics AI, Electronic Health Records)",
        ],
      },
      {
        code: "25B14OE81X",
        name: "Open Elective - 3",
        category: "OEC",
        type: "elective",
        credits: "3.0",
        lectureHours: "3-0-0",
        description: "General elective providing broader societal, organisational, or marketing perspectives.",
        electiveOptions: [
          "Project Management & Agile Methodologies (PMP guidelines, Risk management, Resource allocation)",
          "Organizational Behaviour & Leadership (Workplace psychology, Motivation, Team dynamics)",
          "Digital Marketing & E-Commerce Technologies (SEO, Growth marketing, Analytics, Ad algorithms)",
          "Cyber Laws, Ethics & Environmental Policy (IT Act 2000, Data privacy laws, Digital rights)",
        ],
      },
    ],
  },
];
